// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationLink - ApplicationLink struct
type ApplicationLink struct {
	Href string `json:"href,omitempty"`
	Rel string `json:"rel,omitempty"`
}
