// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// IdpSharingMode - IdpSharingMode struct
type IdpSharingMode struct {
	Policy string `json:"policy,omitempty"`
}
