// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// IdentityProviderTemplateListItem - IdentityProviderTemplateListItem struct
type IdentityProviderTemplateListItem struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Image string `json:"image,omitempty"`
	Category string `json:"category,omitempty"`
	DisplayOrder int32 `json:"displayOrder,omitempty"`
	Services []string `json:"services,omitempty"`
	Self string `json:"self,omitempty"`
}
