// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SharingMode - SharingMode struct
type SharingMode struct {
	Policy string `json:"policy,omitempty"`
	RoleSharing *RoleSharing `json:"roleSharing,omitempty"`
}
