// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// FederatedAuthenticatorPutRequest - FederatedAuthenticatorPutRequest struct
type FederatedAuthenticatorPutRequest struct {
	AuthenticatorId string `json:"authenticatorId,omitempty"`
	Name string `json:"name,omitempty"`
	IsEnabled *bool `json:"isEnabled,omitempty"`
	IsDefault *bool `json:"isDefault,omitempty"`
	DefinedBy string `json:"definedBy,omitempty"`
	Properties []Property `json:"properties,omitempty"`
	Endpoint *Endpoint `json:"endpoint,omitempty"`
}
