// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationCertificate - ApplicationCertificate struct
type ApplicationCertificate struct {
	Type string `json:"type,omitempty"`
	Value string `json:"value,omitempty"`
}
