// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProvisioningResponse - ProvisioningResponse struct
type ProvisioningResponse struct {
	Jit *JustInTimeProvisioning `json:"jit,omitempty"`
	OutboundConnectors *OutboundConnectorListResponse `json:"outboundConnectors,omitempty"`
}
