// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrganizationAttribute - OrganizationAttribute struct
type OrganizationAttribute struct {
	Key string `json:"key"`
	Value string `json:"value"`
}
