// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// IdTokenConfiguration - IdTokenConfiguration struct
type IdTokenConfiguration struct {
	ExpiryInSeconds int64 `json:"expiryInSeconds,omitempty"`
	Audience []string `json:"audience,omitempty"`
	IdTokenSignedResponseAlg string `json:"idTokenSignedResponseAlg,omitempty"`
	Encryption *IdTokenEncryptionConfiguration `json:"encryption,omitempty"`
}
