// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrganizationNameCheckPostResponse - OrganizationNameCheckPostResponse struct
type OrganizationNameCheckPostResponse struct {
	Available bool `json:"available,omitempty"`
}
