// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationRoleMapping - ApplicationRoleMapping struct
type ApplicationRoleMapping struct {
	LocalRole string `json:"localRole,omitempty"`
	ApplicationRole string `json:"applicationRole,omitempty"`
}
