// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HybridFlowConfiguration - HybridFlowConfiguration struct
type HybridFlowConfiguration struct {
	Enable *bool `json:"enable,omitempty"`
	ResponseType string `json:"responseType,omitempty"`
}
