// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TenantModel - TenantModel struct
type TenantModel struct {
	Name string `json:"name,omitempty"`
	Domain string `json:"domain"`
	Owners []Owner `json:"owners"`
}
