// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SamlAttributeProfile - SamlAttributeProfile struct
type SamlAttributeProfile struct {
	Enabled bool `json:"enabled,omitempty"`
	AlwaysIncludeAttributesInResponse bool `json:"alwaysIncludeAttributesInResponse,omitempty"`
	NameFormat string `json:"nameFormat,omitempty"`
}
