// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// IdentityProviderPostRequest - IdentityProviderPostRequest struct
type IdentityProviderPostRequest struct {
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Image string `json:"image,omitempty"`
	TemplateId string `json:"templateId,omitempty"`
	IsPrimary *bool `json:"isPrimary,omitempty"`
	IsFederationHub *bool `json:"isFederationHub,omitempty"`
	HomeRealmIdentifier string `json:"homeRealmIdentifier,omitempty"`
	Certificate *IdpCertificate `json:"certificate,omitempty"`
	Alias string `json:"alias,omitempty"`
	IdpIssuerName string `json:"idpIssuerName,omitempty"`
	Claims *Claims `json:"claims,omitempty"`
	Roles *Roles `json:"roles,omitempty"`
	Groups []IdPGroup `json:"groups,omitempty"`
	FederatedAuthenticators *FederatedAuthenticatorRequest `json:"federatedAuthenticators,omitempty"`
	Provisioning *ProvisioningRequest `json:"provisioning,omitempty"`
	ImplicitAssociation *AssociationRequest `json:"implicitAssociation,omitempty"`
}
