// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MetaProperty - MetaProperty struct
type MetaProperty struct {
	Key string `json:"key,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Description string `json:"description,omitempty"`
	Type string `json:"type,omitempty"`
	DisplayOrder int32 `json:"displayOrder,omitempty"`
	Regex string `json:"regex,omitempty"`
	IsMandatory *bool `json:"isMandatory,omitempty"`
	IsConfidential *bool `json:"isConfidential,omitempty"`
	Options []string `json:"options,omitempty"`
	DefaultValue string `json:"defaultValue,omitempty"`
	SubProperties []MetaProperty `json:"subProperties,omitempty"`
}
