// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationOrgShareConfig - ApplicationOrgShareConfig struct
type ApplicationOrgShareConfig struct {
	OrgId string `json:"orgId,omitempty"`
	Policy string `json:"policy,omitempty"`
	RoleSharing *RoleSharing `json:"roleSharing,omitempty"`
}
