// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// IdpOrgShareConfig - IdpOrgShareConfig struct
type IdpOrgShareConfig struct {
	OrgId string `json:"orgId,omitempty"`
	Policy string `json:"policy,omitempty"`
}
