// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GetOrganizationResponseAncestorPathInner - GetOrganizationResponseAncestorPathInner struct
type GetOrganizationResponseAncestorPathInner struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Depth int32 `json:"depth,omitempty"`
}
