// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ConnectedApp - ConnectedApp struct
type ConnectedApp struct {
	AppId string `json:"appId,omitempty"`
	Self string `json:"self,omitempty"`
}
