// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RequestObjectEncryptionConfiguration - RequestObjectEncryptionConfiguration struct
type RequestObjectEncryptionConfiguration struct {
	Algorithm string `json:"algorithm,omitempty"`
	Method string `json:"method,omitempty"`
}
