// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrganizationDiscoveryAttributes - OrganizationDiscoveryAttributes struct
type OrganizationDiscoveryAttributes struct {
	Attributes []DiscoveryAttribute `json:"attributes,omitempty"`
}
