// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SharedApplicationResponse - SharedApplicationResponse struct
type SharedApplicationResponse struct {
	ApplicationId string `json:"applicationId,omitempty"`
	OrganizationId string `json:"organizationId,omitempty"`
}
