// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationModel - ApplicationModel struct
type ApplicationModel struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	ImageUrl string `json:"imageUrl,omitempty"`
	AccessUrl string `json:"accessUrl,omitempty"`
	LogoutReturnUrl string `json:"logoutReturnUrl,omitempty"`
	TemplateId string `json:"templateId,omitempty"`
	TemplateVersion string `json:"templateVersion,omitempty"`
	IsManagementApp bool `json:"isManagementApp,omitempty"`
	IsB2BSelfServiceApp bool `json:"isB2BSelfServiceApp,omitempty"`
	EnhancedOrgAuthenticationEnabled bool `json:"enhancedOrgAuthenticationEnabled,omitempty"`
	ApplicationEnabled bool `json:"applicationEnabled,omitempty"`
	AssociatedRoles *AssociatedRolesConfig `json:"associatedRoles,omitempty"`
	ClaimConfiguration *ClaimConfiguration `json:"claimConfiguration,omitempty"`
	InboundProtocolConfiguration *InboundProtocols `json:"inboundProtocolConfiguration,omitempty"`
	AuthenticationSequence *AuthenticationSequence `json:"authenticationSequence,omitempty"`
	AdvancedConfigurations *AdvancedApplicationConfiguration `json:"advancedConfigurations,omitempty"`
	ProvisioningConfigurations *ProvisioningConfiguration `json:"provisioningConfigurations,omitempty"`
}
