// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ScriptUpdateModel - ScriptUpdateModel struct
type ScriptUpdateModel struct {
	Script string `json:"script"`
}
