// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MetaFederatedAuthenticatorListItem - MetaFederatedAuthenticatorListItem struct
type MetaFederatedAuthenticatorListItem struct {
	AuthenticatorId string `json:"authenticatorId,omitempty"`
	Name string `json:"name,omitempty"`
	DefinedBy string `json:"definedBy,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Self string `json:"self,omitempty"`
}
