// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AuthorizedAuthorizationDetailsTypes - AuthorizedAuthorizationDetailsTypes struct
type AuthorizedAuthorizationDetailsTypes struct {
	Id string `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
	Name string `json:"name,omitempty"`
}
