// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// FederatedAuthenticatorListItem - FederatedAuthenticatorListItem struct
type FederatedAuthenticatorListItem struct {
	AuthenticatorId string `json:"authenticatorId,omitempty"`
	Name string `json:"name,omitempty"`
	IsEnabled *bool `json:"isEnabled,omitempty"`
	DefinedBy string `json:"definedBy,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Self string `json:"self,omitempty"`
}
