// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomInboundProtocolMetaData - CustomInboundProtocolMetaData struct
type CustomInboundProtocolMetaData struct {
	DisplayName string `json:"displayName,omitempty"`
	ConfigName string `json:"configName,omitempty"`
	Properties []CustomInboundProtocolProperty `json:"properties,omitempty"`
}
