// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AuthenticationStepModel - AuthenticationStepModel struct
type AuthenticationStepModel struct {
	Id int32 `json:"id"`
	Options []Authenticator `json:"options"`
}
