// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RoleMapping - RoleMapping struct
type RoleMapping struct {
	LocalRole string `json:"localRole,omitempty"`
	ApplicationRole string `json:"applicationRole,omitempty"`
}
