// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SubjectConfiguration - SubjectConfiguration struct
type SubjectConfiguration struct {
	SubjectType string `json:"subjectType,omitempty"`
	SectorIdentifierUri string `json:"sectorIdentifierUri,omitempty"`
}
