// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Owner - Owner struct
type Owner struct {
	Username string `json:"username"`
	Password string `json:"password,omitempty"`
	Email string `json:"email"`
	Firstname string `json:"firstname,omitempty"`
	Lastname string `json:"lastname,omitempty"`
	ProvisioningMethod string `json:"provisioningMethod"`
	AdditionalClaims []AdditionalClaims `json:"additionalClaims,omitempty"`
}
