// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// IdpLink - IdpLink struct
type IdpLink struct {
	Href string `json:"href,omitempty"`
	Rel string `json:"rel,omitempty"`
}
