// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CibaMetadata - CibaMetadata struct
type CibaMetadata struct {
	SupportedNotificationChannels []CibaNotificationChannel `json:"supportedNotificationChannels,omitempty"`
}
