// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LoginFlowGenerateRequest - LoginFlowGenerateRequest struct
type LoginFlowGenerateRequest struct {
	AvailableAuthenticators map[string]interface{} `json:"available_authenticators,omitempty"`
	UserClaims []map[string]interface{} `json:"user_claims,omitempty"`
	UserQuery string `json:"user_query,omitempty"`
}
