// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Role - Role struct
type Role struct {
	Id string `json:"id"`
	Name string `json:"name,omitempty"`
}
