// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProvisioningRequest - ProvisioningRequest struct
type ProvisioningRequest struct {
	Jit *JustInTimeProvisioning `json:"jit,omitempty"`
	OutboundConnectors *OutboundProvisioningRequest `json:"outboundConnectors,omitempty"`
}
