// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationSharingPatchRequest - ApplicationSharingPatchRequest struct
type ApplicationSharingPatchRequest struct {
	ApplicationId string `json:"applicationId"`
	Operations []ApplicationSharingPatchOperation `json:"Operations"`
}
