// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ClaimMappings - ClaimMappings struct
type ClaimMappings struct {
	ApplicationClaim string `json:"applicationClaim,omitempty"`
	LocalClaim Claim `json:"localClaim,omitempty"`
}
