// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AssociationRequest - AssociationRequest struct
type AssociationRequest struct {
	IsEnabled *bool `json:"isEnabled,omitempty"`
	LookupAttribute []string `json:"lookupAttribute,omitempty"`
}
