// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CibaAuthenticationRequestConfiguration - CibaAuthenticationRequestConfiguration struct
type CibaAuthenticationRequestConfiguration struct {
	AuthReqExpiryTime int64 `json:"authReqExpiryTime,omitempty"`
	NotificationChannels []string `json:"notificationChannels,omitempty"`
	SkipUserValidation *bool `json:"skipUserValidation,omitempty"`
	AllowFederatedUsers *bool `json:"allowFederatedUsers,omitempty"`
}
