// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RequestObjectConfiguration - RequestObjectConfiguration struct
type RequestObjectConfiguration struct {
	RequestObjectSigningAlg string `json:"requestObjectSigningAlg,omitempty"`
	Encryption *RequestObjectEncryptionConfiguration `json:"encryption,omitempty"`
}
