// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DiscoverableGroup - DiscoverableGroup struct
type DiscoverableGroup struct {
	UserStore string `json:"userStore,omitempty"`
	Groups []GroupBasicInfo `json:"groups,omitempty"`
}
