// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TrustedTokenIssuerResponse - TrustedTokenIssuerResponse struct
type TrustedTokenIssuerResponse struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	TemplateId string `json:"templateId,omitempty"`
	IsEnabled *bool `json:"isEnabled,omitempty"`
	IsPrimary *bool `json:"isPrimary,omitempty"`
	Image string `json:"image,omitempty"`
	IsFederationHub *bool `json:"isFederationHub,omitempty"`
	HomeRealmIdentifier string `json:"homeRealmIdentifier,omitempty"`
	Certificate *IdpCertificate `json:"certificate,omitempty"`
	Alias string `json:"alias,omitempty"`
	Issuer string `json:"issuer,omitempty"`
	Claims *Claims `json:"claims,omitempty"`
	Roles *Roles `json:"roles,omitempty"`
	Groups []IdPGroup `json:"groups,omitempty"`
	FederatedAuthenticators *FederatedAuthenticatorListResponse `json:"federatedAuthenticators,omitempty"`
	Provisioning *ProvisioningResponse `json:"provisioning,omitempty"`
}
