// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Purpose - Purpose struct
type Purpose struct {
	Name string `json:"name"`
	Attributes []TenantAttribute `json:"attributes,omitempty"`
}
