// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Roles - Roles struct
type Roles struct {
	Mappings []IdpRoleMapping `json:"mappings,omitempty"`
	OutboundProvisioningRoles []string `json:"outboundProvisioningRoles,omitempty"`
}
