// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AssociatedRolesConfig - AssociatedRolesConfig struct
type AssociatedRolesConfig struct {
	AllowedAudience string `json:"allowedAudience"`
	Roles []Role `json:"roles,omitempty"`
}
