// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ClaimConfiguration - ClaimConfiguration struct
type ClaimConfiguration struct {
	Dialect string `json:"dialect,omitempty"`
	ClaimMappings []ClaimMappings `json:"claimMappings,omitempty"`
	RequestedClaims []RequestedClaimConfiguration `json:"requestedClaims,omitempty"`
	Subject *SubjectConfig `json:"subject,omitempty"`
	Role *RoleConfig `json:"role,omitempty"`
}
