// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationApplicationSharePostRequest - ApplicationApplicationSharePostRequest struct
type ApplicationApplicationSharePostRequest struct {
	ShareWithAllChildren bool `json:"shareWithAllChildren,omitempty"`
	SharedOrganizations []string `json:"sharedOrganizations,omitempty"`
}
