// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// JustInTimeProvisioning - JustInTimeProvisioning struct
type JustInTimeProvisioning struct {
	IsEnabled *bool `json:"isEnabled,omitempty"`
	Scheme string `json:"scheme,omitempty"`
	Userstore string `json:"userstore,omitempty"`
	AssociateLocalUser *bool `json:"associateLocalUser,omitempty"`
	SkipJITForLookupFailure *bool `json:"skipJITForLookupFailure,omitempty"`
	AccountLookupAttributeMappings []AccountLookupAttributeMapping `json:"accountLookupAttributeMappings,omitempty"`
	AttributeSyncMethod string `json:"attributeSyncMethod,omitempty"`
	IdpGroupSyncMethod string `json:"idpGroupSyncMethod,omitempty"`
}
