// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InboundProtocolListItem - InboundProtocolListItem struct
type InboundProtocolListItem struct {
	Type string `json:"type,omitempty"`
	Name string `json:"name,omitempty"`
	Self string `json:"self,omitempty"`
}
