// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrganizationDiscoveryResponse - OrganizationDiscoveryResponse struct
type OrganizationDiscoveryResponse struct {
	OrganizationId string `json:"organizationId,omitempty"`
	OrganizationName string `json:"organizationName,omitempty"`
	OrgHandle string `json:"orgHandle,omitempty"`
	Attributes []DiscoveryAttribute `json:"attributes,omitempty"`
}
