// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationTemplateModel - ApplicationTemplateModel struct
type ApplicationTemplateModel struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Image string `json:"image,omitempty"`
	AuthenticationProtocol string `json:"authenticationProtocol,omitempty"`
	Types []string `json:"types,omitempty"`
	Category string `json:"category,omitempty"`
	TemplateGroup string `json:"templateGroup,omitempty"`
	DisplayOrder int32 `json:"displayOrder,omitempty"`
	Application ApplicationModel `json:"application,omitempty"`
}
