// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrganizationDiscoveryPostRequest - OrganizationDiscoveryPostRequest struct
type OrganizationDiscoveryPostRequest struct {
	OrganizationId string `json:"organizationId"`
	Attributes []DiscoveryAttribute `json:"attributes"`
}
