// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SamlAssertionConfiguration - SamlAssertionConfiguration struct
type SamlAssertionConfiguration struct {
	NameIdFormat string `json:"nameIdFormat,omitempty"`
	Audiences []string `json:"audiences,omitempty"`
	Recipients []string `json:"recipients,omitempty"`
	DigestAlgorithm string `json:"digestAlgorithm,omitempty"`
	Encryption AssertionEncryptionConfiguration `json:"encryption,omitempty"`
}
