// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OwnerPutModel - OwnerPutModel struct
type OwnerPutModel struct {
	Email string `json:"email"`
	Password string `json:"password,omitempty"`
	Firstname string `json:"firstname"`
	Lastname string `json:"lastname"`
	AdditionalClaims []AdditionalClaims `json:"additionalClaims,omitempty"`
}
