// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// IdpProcessSuccessResponse - IdpProcessSuccessResponse struct
type IdpProcessSuccessResponse struct {
	Status string `json:"status,omitempty"`
	Details string `json:"details,omitempty"`
}
