// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ClaimMappings - ClaimMappings struct
type ClaimMappings struct {
	ApplicationClaim string `json:"applicationClaim"`
	LocalClaim Claim `json:"localClaim"`
}
