// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationBasicOrganizationResponse - ApplicationBasicOrganizationResponse struct
type ApplicationBasicOrganizationResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	OrgHandle string `json:"orgHandle"`
	ParentId string `json:"parentId"`
	Status string `json:"status"`
	Ref string `json:"ref"`
	HasChildren bool `json:"hasChildren"`
	DepthFromRoot int32 `json:"depthFromRoot"`
	SharingMode SharingMode `json:"sharingMode,omitempty"`
	Roles []RoleShareConfig `json:"roles"`
}
