// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OAuth2PkceConfiguration - OAuth2PkceConfiguration struct
type OAuth2PkceConfiguration struct {
	Mandatory *bool `json:"mandatory,omitempty"`
	SupportPlainTransformAlgorithm *bool `json:"supportPlainTransformAlgorithm,omitempty"`
}
