// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrganizationError - OrganizationError struct
type OrganizationError struct {
	Code string `json:"code"`
	Message string `json:"message"`
	Description string `json:"description,omitempty"`
	TraceId string `json:"traceId,omitempty"`
}
