// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AuthorizedApiPatchModel - AuthorizedApiPatchModel struct
type AuthorizedApiPatchModel struct {
	AddedScopes []string `json:"addedScopes,omitempty"`
	RemovedScopes []string `json:"removedScopes,omitempty"`
	AddedAuthorizationDetailsTypes []string `json:"addedAuthorizationDetailsTypes,omitempty"`
	RemovedAuthorizationDetailsTypes []string `json:"removedAuthorizationDetailsTypes,omitempty"`
}
