// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OutboundProvisioningRequest - OutboundProvisioningRequest struct
type OutboundProvisioningRequest struct {
	DefaultConnectorId string `json:"defaultConnectorId,omitempty"`
	Connectors []OutboundConnector `json:"connectors,omitempty"`
}
