// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ParentOrganization - ParentOrganization struct
type ParentOrganization struct {
	Id string `json:"id,omitempty"`
	Ref string `json:"ref,omitempty"`
}
