// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ConfiguredAuthenticatorsModal - ConfiguredAuthenticatorsModal struct
type ConfiguredAuthenticatorsModal struct {
	StepId int32 `json:"stepId,omitempty"`
	LocalAuthenticators []ConfiguredAuthenticator `json:"localAuthenticators,omitempty"`
	FederatedAuthenticators []ConfiguredAuthenticator `json:"federatedAuthenticators,omitempty"`
}
