// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Saml2ServiceProvider - Saml2ServiceProvider struct
type Saml2ServiceProvider struct {
	Issuer string `json:"issuer,omitempty"`
	ServiceProviderQualifier string `json:"serviceProviderQualifier,omitempty"`
	AssertionConsumerUrls []string `json:"assertionConsumerUrls,omitempty"`
	DefaultAssertionConsumerUrl string `json:"defaultAssertionConsumerUrl,omitempty"`
	IdpEntityIdAlias string `json:"idpEntityIdAlias,omitempty"`
	SingleSignOnProfile *SingleSignOnProfile `json:"singleSignOnProfile,omitempty"`
	AttributeProfile *SamlAttributeProfile `json:"attributeProfile,omitempty"`
	SingleLogoutProfile *SingleLogoutProfile `json:"singleLogoutProfile,omitempty"`
	RequestValidation *SamlRequestValidation `json:"requestValidation,omitempty"`
	ResponseSigning *SamlResponseSigning `json:"responseSigning,omitempty"`
	EnableAssertionQueryProfile *bool `json:"enableAssertionQueryProfile,omitempty"`
}
