// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MetaAttributesResponse - MetaAttributesResponse struct
type MetaAttributesResponse struct {
	Links []OrganizationLink `json:"links,omitempty"`
	Attributes []string `json:"attributes,omitempty"`
}
