// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AssertionEncryptionConfiguration - AssertionEncryptionConfiguration struct
type AssertionEncryptionConfiguration struct {
	Enabled *bool `json:"enabled,omitempty"`
	AssertionEncryptionAlgorithm string `json:"assertionEncryptionAlgorithm,omitempty"`
	KeyEncryptionAlgorithm string `json:"keyEncryptionAlgorithm,omitempty"`
}
