// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AuthorizedApiCreationModel - AuthorizedApiCreationModel struct
type AuthorizedApiCreationModel struct {
	Id string `json:"id,omitempty"`
	PolicyIdentifier string `json:"policyIdentifier,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
	AuthorizationDetailsTypes []string `json:"authorizationDetailsTypes,omitempty"`
}
