// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TrustedTokenIssuerPostRequest - TrustedTokenIssuerPostRequest struct
type TrustedTokenIssuerPostRequest struct {
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Image string `json:"image,omitempty"`
	TemplateId string `json:"templateId,omitempty"`
	Certificate *IdpCertificate `json:"certificate,omitempty"`
	Alias string `json:"alias,omitempty"`
	Issuer string `json:"issuer,omitempty"`
	Claims *Claims `json:"claims,omitempty"`
}
