// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationSharingPatchOperation - ApplicationSharingPatchOperation struct
type ApplicationSharingPatchOperation struct {
	Op string `json:"op,omitempty"`
	Path string `json:"path,omitempty"`
	Value []map[string]interface{} `json:"value,omitempty"`
}
