// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AuthenticationSequence - AuthenticationSequence struct
type AuthenticationSequence struct {
	Type string `json:"type,omitempty"`
	Steps []AuthenticationStepModel `json:"steps,omitempty"`
	RequestPathAuthenticators []string `json:"requestPathAuthenticators,omitempty"`
	Script string `json:"script,omitempty"`
	SubjectStepId int32 `json:"subjectStepId,omitempty"`
	AttributeStepId int32 `json:"attributeStepId,omitempty"`
}
