// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OidcLogoutConfiguration - OidcLogoutConfiguration struct
type OidcLogoutConfiguration struct {
	BackChannelLogoutUrl string `json:"backChannelLogoutUrl,omitempty"`
	FrontChannelLogoutUrl string `json:"frontChannelLogoutUrl,omitempty"`
}
