// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationUnshareSelectedRequestBody - ApplicationUnshareSelectedRequestBody struct
type ApplicationUnshareSelectedRequestBody struct {
	ApplicationId string `json:"applicationId"`
	OrgIds []string `json:"orgIds"`
}
