// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationOwner - ApplicationOwner struct
type ApplicationOwner struct {
	Id string `json:"id,omitempty"`
}
