// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// FapiMetadata - FapiMetadata struct
type FapiMetadata struct {
	AllowedFapiProfiles *MetadataProperty `json:"allowedFapiProfiles,omitempty"`
	AllowedSignatureAlgorithms *MetadataProperty `json:"allowedSignatureAlgorithms,omitempty"`
	AllowedEncryptionAlgorithms *MetadataProperty `json:"allowedEncryptionAlgorithms,omitempty"`
	TokenEndpointAuthMethod *ClientAuthenticationMethodMetadata `json:"tokenEndpointAuthMethod,omitempty"`
}
