// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PassiveStsConfiguration - PassiveStsConfiguration struct
type PassiveStsConfiguration struct {
	Realm string `json:"realm,omitempty"`
	ReplyTo string `json:"replyTo,omitempty"`
	ReplyToLogout string `json:"replyToLogout,omitempty"`
}
