// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationShareAllRequestBody - ApplicationShareAllRequestBody struct
type ApplicationShareAllRequestBody struct {
	ApplicationId string `json:"applicationId,omitempty"`
	Policy string `json:"policy,omitempty"`
	RoleSharing RoleSharing `json:"roleSharing,omitempty"`
}
