// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TokenExchangeConfiguration - TokenExchangeConfiguration struct
type TokenExchangeConfiguration struct {
	RestrictScopeIssuanceForFederatedTokens bool `json:"restrictScopeIssuanceForFederatedTokens,omitempty"`
}
