// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GrantType - GrantType struct
type GrantType struct {
	Name string `json:"name,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	PublicClientAllowed bool `json:"publicClientAllowed,omitempty"`
}
