// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ClientAuthenticationMethodMetadata - ClientAuthenticationMethodMetadata struct
type ClientAuthenticationMethodMetadata struct {
	Options []ClientAuthenticationMethod `json:"options,omitempty"`
}
