// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SharedApplicationsResponse - SharedApplicationsResponse struct
type SharedApplicationsResponse struct {
	SharedApplications []SharedApplicationResponse `json:"sharedApplications,omitempty"`
}
