// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SamlResponseSigning - SamlResponseSigning struct
type SamlResponseSigning struct {
	Enabled *bool `json:"enabled,omitempty"`
	SigningAlgorithm string `json:"signingAlgorithm,omitempty"`
}
