// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationSharingMode - ApplicationSharingMode struct
type ApplicationSharingMode struct {
	Policy string `json:"policy,omitempty"`
	RoleSharing *RoleSharing `json:"roleSharing,omitempty"`
}
