// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrganizationCheckResponse - OrganizationCheckResponse struct
type OrganizationCheckResponse struct {
	Available bool `json:"available,omitempty"`
}
