// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Claim - Claim struct
type Claim struct {
	Id string `json:"id,omitempty"`
	Uri string `json:"uri"`
	DisplayName string `json:"displayName,omitempty"`
}
