// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InboundScimProvisioningConfiguration - InboundScimProvisioningConfiguration struct
type InboundScimProvisioningConfiguration struct {
	ProxyMode *bool `json:"proxyMode,omitempty"`
	ProvisioningUserstoreDomain string `json:"provisioningUserstoreDomain,omitempty"`
}
