// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrganizationDiscoveryResponse - OrganizationDiscoveryResponse struct
type OrganizationDiscoveryResponse struct {
	OrganizationId string `json:"organizationId"`
	OrganizationName string `json:"organizationName"`
	OrgHandle string `json:"orgHandle"`
	Attributes []DiscoveryAttribute `json:"attributes"`
}
