// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TenantsListResponse - TenantsListResponse struct
type TenantsListResponse struct {
	TotalResults int32 `json:"totalResults,omitempty"`
	StartIndex int32 `json:"startIndex,omitempty"`
	Count int32 `json:"count,omitempty"`
	Links []TenantLink `json:"links,omitempty"`
	Tenants []TenantListItem `json:"tenants,omitempty"`
}
