// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OwnerInfoResponse - OwnerInfoResponse struct
type OwnerInfoResponse struct {
	Id string `json:"id,omitempty"`
	Username string `json:"username,omitempty"`
	Email string `json:"email,omitempty"`
	Firstname string `json:"firstname,omitempty"`
	Lastname string `json:"lastname,omitempty"`
	AdditionalClaims []AdditionalClaims `json:"additionalClaims,omitempty"`
}
