// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// FederatedAuthenticatorListResponse - FederatedAuthenticatorListResponse struct
type FederatedAuthenticatorListResponse struct {
	DefaultAuthenticatorId string `json:"defaultAuthenticatorId,omitempty"`
	Authenticators []FederatedAuthenticatorListItem `json:"authenticators,omitempty"`
}
