// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RoleConfig - RoleConfig struct
type RoleConfig struct {
	Mappings []ApplicationRoleMapping `json:"mappings,omitempty"`
	IncludeUserDomain *bool `json:"includeUserDomain,omitempty"`
	Claim *Claim `json:"claim,omitempty"`
}
