// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GroupBasicInfo - GroupBasicInfo struct
type GroupBasicInfo struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
