// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InboundProtocolListItem - InboundProtocolListItem struct
type InboundProtocolListItem struct {
	Type string `json:"type"`
	Name string `json:"name"`
	Self string `json:"self"`
}
