// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomInboundProtocolConfiguration - CustomInboundProtocolConfiguration struct
type CustomInboundProtocolConfiguration struct {
	Name string `json:"name,omitempty"`
	ConfigName string `json:"configName,omitempty"`
	Properties []PropertyModel `json:"properties,omitempty"`
}
