// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AdditionalSpProperty - AdditionalSpProperty struct
type AdditionalSpProperty struct {
	Name string `json:"name"`
	Value string `json:"value"`
	DisplayName string `json:"displayName,omitempty"`
}
