// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &ApplicationMetaInboundProtocolSamlDataSource{}

func NewApplicationMetaInboundProtocolSamlDataSource() datasource.DataSource {
	return &ApplicationMetaInboundProtocolSamlDataSource{}
}

type ApplicationMetaInboundProtocolSamlDataSource struct {
	client *client.Client
}

func (d *ApplicationMetaInboundProtocolSamlDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application_meta_inbound_protocol_saml"
}

func (d *ApplicationMetaInboundProtocolSamlDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a application_meta_inbound_protocol_saml data source.",
		Attributes: map[string]schema.Attribute{
			"default_name_id_format": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"certificate_alias": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"response_signing_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"response_digest_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"assertion_encryption_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"key_encryption_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
		},
	}
}

func (d *ApplicationMetaInboundProtocolSamlDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *ApplicationMetaInboundProtocolSamlDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config ApplicationMetaInboundProtocolSamlModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", "/applications/meta/inbound-protocols/saml", nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading application_meta_inbound_protocol_saml", err.Error())
		return
	}

	var result client.SamlMetaData
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read application_meta_inbound_protocol_saml data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
