// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ApplicationExportModel is the Terraform model for application_export.
type ApplicationExportModel struct {
	ApplicationId types.String `tfsdk:"application_id"`
}



