// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationAuthorizedApiModel is the Terraform model for application_authorized_api.
type ApplicationAuthorizedApiModel struct {
	Id types.String `tfsdk:"id"`
	PolicyIdentifier types.String `tfsdk:"policy_identifier"`
	Scopes jsontypes.Normalized `tfsdk:"scopes"`
	AuthorizationDetailsTypes jsontypes.Normalized `tfsdk:"authorization_details_types"`
	ApplicationId types.String `tfsdk:"application_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *ApplicationAuthorizedApiModel) ToClientModel() (*client.AuthorizedApiCreationModel, error) {
	out := &client.AuthorizedApiCreationModel{}
	if !m.Id.IsNull() && !m.Id.IsUnknown() {
		out.Id = m.Id.ValueString()
	}
	if !m.PolicyIdentifier.IsNull() && !m.PolicyIdentifier.IsUnknown() {
		out.PolicyIdentifier = m.PolicyIdentifier.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Scopes.IsNull() && !m.Scopes.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Scopes.ValueString()), &out.Scopes); err != nil {
			return out, fmt.Errorf("scopes: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.AuthorizationDetailsTypes.IsNull() && !m.AuthorizationDetailsTypes.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AuthorizationDetailsTypes.ValueString()), &out.AuthorizationDetailsTypes); err != nil {
			return out, fmt.Errorf("authorization_details_types: %w", err)
		}
	}
	return out, nil
}

