// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationInboundProtocolOidcModel is the Terraform model for application_inbound_protocol_oidc.
type ApplicationInboundProtocolOidcModel struct {
	ClientId types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	ClientSecretExpiresAt types.Int64 `tfsdk:"client_secret_expires_at"`
	MultipleClientSecretsConfigured types.Bool `tfsdk:"multiple_client_secrets_configured"`
	State types.String `tfsdk:"state"`
	GrantTypes jsontypes.Normalized `tfsdk:"grant_types"`
	CallbackURLs jsontypes.Normalized `tfsdk:"callback_urls"`
	AllowedOrigins jsontypes.Normalized `tfsdk:"allowed_origins"`
	PublicClient types.Bool `tfsdk:"public_client"`
	Pkce jsontypes.Normalized `tfsdk:"pkce"`
	AccessToken jsontypes.Normalized `tfsdk:"access_token"`
	HybridFlow jsontypes.Normalized `tfsdk:"hybrid_flow"`
	RefreshToken jsontypes.Normalized `tfsdk:"refresh_token"`
	SubjectToken jsontypes.Normalized `tfsdk:"subject_token"`
	IdToken jsontypes.Normalized `tfsdk:"id_token"`
	Logout jsontypes.Normalized `tfsdk:"logout"`
	ValidateRequestObjectSignature types.Bool `tfsdk:"validate_request_object_signature"`
	ScopeValidators jsontypes.Normalized `tfsdk:"scope_validators"`
	ClientAuthentication jsontypes.Normalized `tfsdk:"client_authentication"`
	RequestObject jsontypes.Normalized `tfsdk:"request_object"`
	PushAuthorizationRequest jsontypes.Normalized `tfsdk:"push_authorization_request"`
	Subject jsontypes.Normalized `tfsdk:"subject"`
	IsFAPIApplication types.Bool `tfsdk:"is_fapi_application"`
	FapiProfile types.String `tfsdk:"fapi_profile"`
	CibaAuthenticationRequest jsontypes.Normalized `tfsdk:"ciba_authentication_request"`
	Issuer jsontypes.Normalized `tfsdk:"issuer"`
	TokenExchange jsontypes.Normalized `tfsdk:"token_exchange"`
	ApplicationId types.String `tfsdk:"application_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *ApplicationInboundProtocolOidcModel) ToClientModel() (*client.OpenIdConnectConfiguration, error) {
	out := &client.OpenIdConnectConfiguration{}
	if !m.ClientId.IsNull() && !m.ClientId.IsUnknown() {
		out.ClientId = m.ClientId.ValueString()
	}
	if !m.ClientSecret.IsNull() && !m.ClientSecret.IsUnknown() {
		out.ClientSecret = m.ClientSecret.ValueString()
	}
	if !m.ClientSecretExpiresAt.IsNull() && !m.ClientSecretExpiresAt.IsUnknown() {
		out.ClientSecretExpiresAt = int64(m.ClientSecretExpiresAt.ValueInt64())
	}
	if !m.MultipleClientSecretsConfigured.IsNull() && !m.MultipleClientSecretsConfigured.IsUnknown() {
		out.MultipleClientSecretsConfigured = m.MultipleClientSecretsConfigured.ValueBool()
	}
	if !m.State.IsNull() && !m.State.IsUnknown() {
		out.State = m.State.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.GrantTypes.IsNull() && !m.GrantTypes.IsUnknown() {
		if err := json.Unmarshal([]byte(m.GrantTypes.ValueString()), &out.GrantTypes); err != nil {
			return out, fmt.Errorf("grant_types: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.CallbackURLs.IsNull() && !m.CallbackURLs.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CallbackURLs.ValueString()), &out.CallbackURLs); err != nil {
			return out, fmt.Errorf("callback_urls: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.AllowedOrigins.IsNull() && !m.AllowedOrigins.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AllowedOrigins.ValueString()), &out.AllowedOrigins); err != nil {
			return out, fmt.Errorf("allowed_origins: %w", err)
		}
	}
	if !m.PublicClient.IsNull() && !m.PublicClient.IsUnknown() {
		out.PublicClient = m.PublicClient.ValueBool()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Pkce.IsNull() && !m.Pkce.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Pkce.ValueString()), &out.Pkce); err != nil {
			return out, fmt.Errorf("pkce: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.AccessToken.IsNull() && !m.AccessToken.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AccessToken.ValueString()), &out.AccessToken); err != nil {
			return out, fmt.Errorf("access_token: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.HybridFlow.IsNull() && !m.HybridFlow.IsUnknown() {
		if err := json.Unmarshal([]byte(m.HybridFlow.ValueString()), &out.HybridFlow); err != nil {
			return out, fmt.Errorf("hybrid_flow: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.RefreshToken.IsNull() && !m.RefreshToken.IsUnknown() {
		if err := json.Unmarshal([]byte(m.RefreshToken.ValueString()), &out.RefreshToken); err != nil {
			return out, fmt.Errorf("refresh_token: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.SubjectToken.IsNull() && !m.SubjectToken.IsUnknown() {
		if err := json.Unmarshal([]byte(m.SubjectToken.ValueString()), &out.SubjectToken); err != nil {
			return out, fmt.Errorf("subject_token: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.IdToken.IsNull() && !m.IdToken.IsUnknown() {
		if err := json.Unmarshal([]byte(m.IdToken.ValueString()), &out.IdToken); err != nil {
			return out, fmt.Errorf("id_token: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Logout.IsNull() && !m.Logout.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Logout.ValueString()), &out.Logout); err != nil {
			return out, fmt.Errorf("logout: %w", err)
		}
	}
	if !m.ValidateRequestObjectSignature.IsNull() && !m.ValidateRequestObjectSignature.IsUnknown() {
		out.ValidateRequestObjectSignature = m.ValidateRequestObjectSignature.ValueBool()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.ScopeValidators.IsNull() && !m.ScopeValidators.IsUnknown() {
		if err := json.Unmarshal([]byte(m.ScopeValidators.ValueString()), &out.ScopeValidators); err != nil {
			return out, fmt.Errorf("scope_validators: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.ClientAuthentication.IsNull() && !m.ClientAuthentication.IsUnknown() {
		if err := json.Unmarshal([]byte(m.ClientAuthentication.ValueString()), &out.ClientAuthentication); err != nil {
			return out, fmt.Errorf("client_authentication: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.RequestObject.IsNull() && !m.RequestObject.IsUnknown() {
		if err := json.Unmarshal([]byte(m.RequestObject.ValueString()), &out.RequestObject); err != nil {
			return out, fmt.Errorf("request_object: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.PushAuthorizationRequest.IsNull() && !m.PushAuthorizationRequest.IsUnknown() {
		if err := json.Unmarshal([]byte(m.PushAuthorizationRequest.ValueString()), &out.PushAuthorizationRequest); err != nil {
			return out, fmt.Errorf("push_authorization_request: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Subject.IsNull() && !m.Subject.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Subject.ValueString()), &out.Subject); err != nil {
			return out, fmt.Errorf("subject: %w", err)
		}
	}
	if !m.IsFAPIApplication.IsNull() && !m.IsFAPIApplication.IsUnknown() {
		out.IsFAPIApplication = m.IsFAPIApplication.ValueBool()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.CibaAuthenticationRequest.IsNull() && !m.CibaAuthenticationRequest.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CibaAuthenticationRequest.ValueString()), &out.CibaAuthenticationRequest); err != nil {
			return out, fmt.Errorf("ciba_authentication_request: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Issuer.IsNull() && !m.Issuer.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Issuer.ValueString()), &out.Issuer); err != nil {
			return out, fmt.Errorf("issuer: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.TokenExchange.IsNull() && !m.TokenExchange.IsUnknown() {
		if err := json.Unmarshal([]byte(m.TokenExchange.ValueString()), &out.TokenExchange); err != nil {
			return out, fmt.Errorf("token_exchange: %w", err)
		}
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationInboundProtocolOidcModel) FromClientModel(c *client.OpenIdConnectConfiguration) {
	m.ClientId = types.StringValue(c.ClientId)
	m.ClientSecret = types.StringValue(c.ClientSecret)
	m.ClientSecretExpiresAt = types.Int64Value(int64(c.ClientSecretExpiresAt))
	m.MultipleClientSecretsConfigured = types.BoolValue(c.MultipleClientSecretsConfigured)
	m.State = types.StringValue(c.State)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.GrantTypes); err == nil {
		m.GrantTypes = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.CallbackURLs); err == nil {
		m.CallbackURLs = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.AllowedOrigins); err == nil {
		m.AllowedOrigins = jsontypes.NewNormalizedValue(string(encoded))
	}
	m.PublicClient = types.BoolValue(c.PublicClient)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.Pkce); err == nil {
		m.Pkce = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.AccessToken); err == nil {
		m.AccessToken = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.HybridFlow); err == nil {
		m.HybridFlow = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.RefreshToken); err == nil {
		m.RefreshToken = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.SubjectToken); err == nil {
		m.SubjectToken = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.IdToken); err == nil {
		m.IdToken = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.Logout); err == nil {
		m.Logout = jsontypes.NewNormalizedValue(string(encoded))
	}
	m.ValidateRequestObjectSignature = types.BoolValue(c.ValidateRequestObjectSignature)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.ScopeValidators); err == nil {
		m.ScopeValidators = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.ClientAuthentication); err == nil {
		m.ClientAuthentication = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.RequestObject); err == nil {
		m.RequestObject = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.PushAuthorizationRequest); err == nil {
		m.PushAuthorizationRequest = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.Subject); err == nil {
		m.Subject = jsontypes.NewNormalizedValue(string(encoded))
	}
	m.IsFAPIApplication = types.BoolValue(c.IsFAPIApplication)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.CibaAuthenticationRequest); err == nil {
		m.CibaAuthenticationRequest = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.Issuer); err == nil {
		m.Issuer = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.TokenExchange); err == nil {
		m.TokenExchange = jsontypes.NewNormalizedValue(string(encoded))
	}
}
