// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationsUnshareWithAllModel is the Terraform model for applications_unshare_with_all.
type ApplicationsUnshareWithAllModel struct {
	Status types.String `tfsdk:"status"`
	Details types.String `tfsdk:"details"`
	ApplicationId types.String `tfsdk:"application_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *ApplicationsUnshareWithAllModel) ToClientModel() (*client.ApplicationUnshareAllRequestBody, error) {
	out := &client.ApplicationUnshareAllRequestBody{}
	if !m.ApplicationId.IsNull() && !m.ApplicationId.IsUnknown() {
		out.ApplicationId = m.ApplicationId.ValueString()
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationsUnshareWithAllModel) FromClientModel(c *client.ApplicationProcessSuccessResponse) {
	m.Status = types.StringValue(c.Status)
	m.Details = types.StringValue(c.Details)
}
