// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationShareWithAllModel is the Terraform model for application_share_with_all.
type ApplicationShareWithAllModel struct {
	Status types.String `tfsdk:"status"`
	Details types.String `tfsdk:"details"`
	ApplicationId types.String `tfsdk:"application_id"`
	Policy types.String `tfsdk:"policy"`
	RoleSharing jsontypes.Normalized `tfsdk:"role_sharing"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *ApplicationShareWithAllModel) ToClientModel() (*client.ApplicationShareAllRequestBody, error) {
	out := &client.ApplicationShareAllRequestBody{}
	if !m.ApplicationId.IsNull() && !m.ApplicationId.IsUnknown() {
		out.ApplicationId = m.ApplicationId.ValueString()
	}
	if !m.Policy.IsNull() && !m.Policy.IsUnknown() {
		out.Policy = m.Policy.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.RoleSharing.IsNull() && !m.RoleSharing.IsUnknown() {
		if err := json.Unmarshal([]byte(m.RoleSharing.ValueString()), &out.RoleSharing); err != nil {
			return out, fmt.Errorf("role_sharing: %w", err)
		}
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationShareWithAllModel) FromClientModel(c *client.ProcessSuccessResponse) {
	m.Status = types.StringValue(c.Status)
	m.Details = types.StringValue(c.Details)
}
