// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &ApplicationsLoginflowGenerateDataSource{}

func NewApplicationsLoginflowGenerateDataSource() datasource.DataSource {
	return &ApplicationsLoginflowGenerateDataSource{}
}

type ApplicationsLoginflowGenerateDataSource struct {
	client *client.Client
}

func (d *ApplicationsLoginflowGenerateDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_applications_loginflow_generate"
}

func (d *ApplicationsLoginflowGenerateDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a applications_loginflow_generate data source.",
		Attributes: map[string]schema.Attribute{
			"operation_id": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"available_authenticators": schema.StringAttribute{
				Computed:    true,
				Description: "Available authenticators of the organization. It&#39;s expected to provide the authenticator name, description, and the IDP. ",
			},
			"user_claims": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Metadata of the available user claims for the organization.  Provide the claim URI and a human-readable description of the claim. ",
			},
			"user_query": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
		},
	}
}

func (d *ApplicationsLoginflowGenerateDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *ApplicationsLoginflowGenerateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	resp.Diagnostics.AddError("Not Supported", "Read is not supported for applications_loginflow_generate")
}
