// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationsMetaInboundProtocolModel is the Terraform model for applications_meta_inbound_protocol.
type ApplicationsMetaInboundProtocolModel struct {
	DisplayName types.String `tfsdk:"display_name"`
	ConfigName types.String `tfsdk:"config_name"`
	Properties jsontypes.Normalized `tfsdk:"properties"`
	InboundProtocolId types.String `tfsdk:"inbound_protocol_id"`
}



// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationsMetaInboundProtocolModel) FromClientModel(c *client.CustomInboundProtocolMetaData) {
	m.DisplayName = types.StringValue(c.DisplayName)
	m.ConfigName = types.StringValue(c.ConfigName)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.Properties); err == nil {
		m.Properties = jsontypes.NewNormalizedValue(string(encoded))
	}
}
