// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationInboundProtocolsOidcSecretModel is the Terraform model for application_inbound_protocols_oidc_secret.
type ApplicationInboundProtocolsOidcSecretModel struct {
	SecretId types.String `tfsdk:"secret_id"`
	SecretValue types.String `tfsdk:"secret_value"`
	ExpiresAt types.Int64 `tfsdk:"expires_at"`
	CreatedAt types.Int64 `tfsdk:"created_at"`
	Status types.String `tfsdk:"status"`
	Latest types.Bool `tfsdk:"latest"`
	ApplicationId types.String `tfsdk:"application_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *ApplicationInboundProtocolsOidcSecretModel) ToClientModel() (*client.ClientSecretCreationRequest, error) {
	out := &client.ClientSecretCreationRequest{}
	if !m.ExpiresAt.IsNull() && !m.ExpiresAt.IsUnknown() {
		out.ExpiresAt = int64(m.ExpiresAt.ValueInt64())
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationInboundProtocolsOidcSecretModel) FromClientModel(c *client.ClientSecretResponse) {
	m.SecretId = types.StringValue(c.SecretId)
	m.SecretValue = types.StringValue(c.SecretValue)
	m.ExpiresAt = types.Int64Value(int64(c.ExpiresAt))
	m.CreatedAt = types.Int64Value(int64(c.CreatedAt))
	m.Status = types.StringValue(c.Status)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.Latest != nil {
		m.Latest = types.BoolValue(*c.Latest)
	} else if m.Latest.IsUnknown() {
		m.Latest = types.BoolNull()
	}
}
