// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationsMetaInboundProtocolsOidcModel is the Terraform model for applications_meta_inbound_protocols_oidc.
type ApplicationsMetaInboundProtocolsOidcModel struct {
	AllowedGrantTypes jsontypes.Normalized `tfsdk:"allowed_grant_types"`
	DefaultUserAccessTokenExpiryTime types.String `tfsdk:"default_user_access_token_expiry_time"`
	DefaultApplicationAccessTokenExpiryTime types.String `tfsdk:"default_application_access_token_expiry_time"`
	DefaultRefreshTokenExpiryTime types.String `tfsdk:"default_refresh_token_expiry_time"`
	DefaultIdTokenExpiryTime types.String `tfsdk:"default_id_token_expiry_time"`
	IdTokenEncryptionAlgorithm jsontypes.Normalized `tfsdk:"id_token_encryption_algorithm"`
	IdTokenEncryptionMethod jsontypes.Normalized `tfsdk:"id_token_encryption_method"`
	ScopeValidators jsontypes.Normalized `tfsdk:"scope_validators"`
	AccessTokenType jsontypes.Normalized `tfsdk:"access_token_type"`
	AccessTokenBindingType jsontypes.Normalized `tfsdk:"access_token_binding_type"`
	TokenEndpointAuthMethod jsontypes.Normalized `tfsdk:"token_endpoint_auth_method"`
	TokenEndpointAllowReusePvtKeyJwt types.Bool `tfsdk:"token_endpoint_allow_reuse_pvt_key_jwt"`
	TokenEndpointSignatureAlgorithm jsontypes.Normalized `tfsdk:"token_endpoint_signature_algorithm"`
	IdTokenSignatureAlgorithm jsontypes.Normalized `tfsdk:"id_token_signature_algorithm"`
	RequestObjectSignatureAlgorithm jsontypes.Normalized `tfsdk:"request_object_signature_algorithm"`
	RequestObjectEncryptionAlgorithm jsontypes.Normalized `tfsdk:"request_object_encryption_algorithm"`
	RequestObjectEncryptionMethod jsontypes.Normalized `tfsdk:"request_object_encryption_method"`
	SubjectType jsontypes.Normalized `tfsdk:"subject_type"`
	FapiMetadata jsontypes.Normalized `tfsdk:"fapi_metadata"`
	CibaMetadata jsontypes.Normalized `tfsdk:"ciba_metadata"`
	AllowedIssuers jsontypes.Normalized `tfsdk:"allowed_issuers"`
}


// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationsMetaInboundProtocolsOidcModel) FromClientModel(c *client.OidcMetaData) {
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.AllowedGrantTypes); err == nil {
		m.AllowedGrantTypes = jsontypes.NewNormalizedValue(string(encoded))
	}
	m.DefaultUserAccessTokenExpiryTime = types.StringValue(c.DefaultUserAccessTokenExpiryTime)
	m.DefaultApplicationAccessTokenExpiryTime = types.StringValue(c.DefaultApplicationAccessTokenExpiryTime)
	m.DefaultRefreshTokenExpiryTime = types.StringValue(c.DefaultRefreshTokenExpiryTime)
	m.DefaultIdTokenExpiryTime = types.StringValue(c.DefaultIdTokenExpiryTime)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.IdTokenEncryptionAlgorithm); err == nil {
		m.IdTokenEncryptionAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.IdTokenEncryptionMethod); err == nil {
		m.IdTokenEncryptionMethod = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.ScopeValidators); err == nil {
		m.ScopeValidators = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.AccessTokenType); err == nil {
		m.AccessTokenType = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.AccessTokenBindingType); err == nil {
		m.AccessTokenBindingType = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.TokenEndpointAuthMethod); err == nil {
		m.TokenEndpointAuthMethod = jsontypes.NewNormalizedValue(string(encoded))
	}
	m.TokenEndpointAllowReusePvtKeyJwt = types.BoolValue(c.TokenEndpointAllowReusePvtKeyJwt)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.TokenEndpointSignatureAlgorithm); err == nil {
		m.TokenEndpointSignatureAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.IdTokenSignatureAlgorithm); err == nil {
		m.IdTokenSignatureAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.RequestObjectSignatureAlgorithm); err == nil {
		m.RequestObjectSignatureAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.RequestObjectEncryptionAlgorithm); err == nil {
		m.RequestObjectEncryptionAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.RequestObjectEncryptionMethod); err == nil {
		m.RequestObjectEncryptionMethod = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.SubjectType); err == nil {
		m.SubjectType = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.FapiMetadata); err == nil {
		m.FapiMetadata = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.CibaMetadata); err == nil {
		m.CibaMetadata = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.AllowedIssuers); err == nil {
		m.AllowedIssuers = jsontypes.NewNormalizedValue(string(encoded))
	}
}
