// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationsMetaInboundProtocolsWsTrustModel is the Terraform model for applications_meta_inbound_protocols_ws_trust.
type ApplicationsMetaInboundProtocolsWsTrustModel struct {
	CertificateAlias jsontypes.Normalized `tfsdk:"certificate_alias"`
}



// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationsMetaInboundProtocolsWsTrustModel) FromClientModel(c *client.WsTrustMetaData) {
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.CertificateAlias); err == nil {
		if m.CertificateAlias.IsNull() || m.CertificateAlias.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.CertificateAlias.ValueString()) {
			m.CertificateAlias = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
