// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &ApplicationInboundProtocolsPassiveStsDataSource{}

func NewApplicationInboundProtocolsPassiveStsDataSource() datasource.DataSource {
	return &ApplicationInboundProtocolsPassiveStsDataSource{}
}

type ApplicationInboundProtocolsPassiveStsDataSource struct {
	client *client.Client
}

func (d *ApplicationInboundProtocolsPassiveStsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application_inbound_protocols_passive_sts"
}

func (d *ApplicationInboundProtocolsPassiveStsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a application_inbound_protocols_passive_sts data source.",
		Attributes: map[string]schema.Attribute{
			"realm": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"reply_to": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"reply_to_logout": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"application_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the applicationId.",
			},
		},
	}
}

func (d *ApplicationInboundProtocolsPassiveStsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *ApplicationInboundProtocolsPassiveStsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config ApplicationInboundProtocolsPassiveStsModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/applications/%v/inbound-protocols/passive-sts", config.ApplicationId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading application_inbound_protocols_passive_sts", err.Error())
		return
	}

	var result client.PassiveStsConfiguration
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read application_inbound_protocols_passive_sts data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
