// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ApplicationInboundProtocolModel is the Terraform model for application_inbound_protocol.
type ApplicationInboundProtocolModel struct {
	ApplicationId types.String `tfsdk:"application_id"`
}


