// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationsMetaInboundProtocolsSamlModel is the Terraform model for applications_meta_inbound_protocols_saml.
type ApplicationsMetaInboundProtocolsSamlModel struct {
	DefaultNameIdFormat types.String `tfsdk:"default_name_id_format"`
	CertificateAlias jsontypes.Normalized `tfsdk:"certificate_alias"`
	ResponseSigningAlgorithm jsontypes.Normalized `tfsdk:"response_signing_algorithm"`
	ResponseDigestAlgorithm jsontypes.Normalized `tfsdk:"response_digest_algorithm"`
	AssertionEncryptionAlgorithm jsontypes.Normalized `tfsdk:"assertion_encryption_algorithm"`
	KeyEncryptionAlgorithm jsontypes.Normalized `tfsdk:"key_encryption_algorithm"`
}



// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationsMetaInboundProtocolsSamlModel) FromClientModel(c *client.SamlMetaData) {
	m.DefaultNameIdFormat = types.StringValue(c.DefaultNameIdFormat)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.CertificateAlias); err == nil {
		m.CertificateAlias = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.ResponseSigningAlgorithm); err == nil {
		m.ResponseSigningAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.ResponseDigestAlgorithm); err == nil {
		m.ResponseDigestAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.AssertionEncryptionAlgorithm); err == nil {
		m.AssertionEncryptionAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.KeyEncryptionAlgorithm); err == nil {
		m.KeyEncryptionAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
	}
}
