// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &ApplicationShareResource{}
var _ resource.ResourceWithImportState = &ApplicationShareResource{}

func NewApplicationShareResource() resource.Resource {
	return &ApplicationShareResource{}
}

type ApplicationShareResource struct {
	client *client.Client
}

func (r *ApplicationShareResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application_share"
}

func (r *ApplicationShareResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a application_share resource.",
		Attributes: map[string]schema.Attribute{
			"share_with_all_children": schema.BoolAttribute{
				Optional:    true,
				Description: "",
			},
			"shared_organizations": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"application_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the parent applicationId.",
			},
			"shared_organization_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Identifier of the shared-organization.",
			},
		},
	}
}

func (r *ApplicationShareResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *ApplicationShareResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ApplicationShareModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid application_share configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", fmt.Sprintf("/applications/%v/share", plan.ApplicationId.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating application_share", err.Error())
		return
	}

	// A create that answers 201 with nothing but a Location header -- WSO2 does
	// this for tenants and applications. The identifier is in that header, and
	// everything else the server assigned has to be fetched.
	if len(respBody) == 0 {
		plan.SharedOrganizationId = types.StringValue(client.IDFromLocation(location))
	}

	_ = respBody

	tflog.Trace(ctx, "created application_share resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ApplicationShareResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// No read endpoint available; keep existing state as-is.
}

func (r *ApplicationShareResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// No update endpoint: nothing here can change on the server, so the plan
	// stands. But EVERY Computed attribute is unknown in a plan, and a provider
	// must answer known values after an apply -- persisting the plan as it
	// stands earns "Provider returned invalid result object after apply". The
	// known values come from a read.
	var plan ApplicationShareModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ApplicationShareResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ApplicationShareModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/applications/%v/share/%v", state.ApplicationId.ValueString(), state.SharedOrganizationId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting application_share", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted application_share resource")
}

func (r *ApplicationShareResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("shared_organization_id"), req, resp)
}
