// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationMetaAdaptiveAuthTemplateModel is the Terraform model for application_meta_adaptive_auth_template.
type ApplicationMetaAdaptiveAuthTemplateModel struct {
	TemplatesJSON types.String `tfsdk:"templates_json"`
}


// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationMetaAdaptiveAuthTemplateModel) FromClientModel(c *client.AdaptiveAuthTemplates) {
	m.TemplatesJSON = types.StringValue(c.TemplatesJSON)
}
