// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &ApplicationsMetaInboundProtocolsOidcResource{}
var _ resource.ResourceWithImportState = &ApplicationsMetaInboundProtocolsOidcResource{}

func NewApplicationsMetaInboundProtocolsOidcResource() resource.Resource {
	return &ApplicationsMetaInboundProtocolsOidcResource{}
}

type ApplicationsMetaInboundProtocolsOidcResource struct {
	client *client.Client
}

func (r *ApplicationsMetaInboundProtocolsOidcResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_applications_meta_inbound_protocols_oidc"
}

func (r *ApplicationsMetaInboundProtocolsOidcResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a applications_meta_inbound_protocols_oidc resource.",
		Attributes: map[string]schema.Attribute{
			"allowed_grant_types": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"default_user_access_token_expiry_time": schema.StringAttribute{
				Optional:    true,
				Description: "",
			},
			"default_application_access_token_expiry_time": schema.StringAttribute{
				Optional:    true,
				Description: "",
			},
			"default_refresh_token_expiry_time": schema.StringAttribute{
				Optional:    true,
				Description: "",
			},
			"default_id_token_expiry_time": schema.StringAttribute{
				Optional:    true,
				Description: "",
			},
			"id_token_encryption_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"id_token_encryption_method": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"scope_validators": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"access_token_type": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"access_token_binding_type": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"token_endpoint_auth_method": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"token_endpoint_allow_reuse_pvt_key_jwt": schema.StringAttribute{
				Optional:    true,
				Description: "",
			},
			"token_endpoint_signature_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"id_token_signature_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"request_object_signature_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"request_object_encryption_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"request_object_encryption_method": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"subject_type": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"fapi_metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"ciba_metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"allowed_issuers": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
		},
	}
}

func (r *ApplicationsMetaInboundProtocolsOidcResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *ApplicationsMetaInboundProtocolsOidcResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for applications_meta_inbound_protocols_oidc")
}

func (r *ApplicationsMetaInboundProtocolsOidcResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ApplicationsMetaInboundProtocolsOidcModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", "/applications/meta/inbound-protocols/oidc", nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading applications_meta_inbound_protocols_oidc", err.Error())
		return
	}

	var result client.OidcMetaData
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ApplicationsMetaInboundProtocolsOidcResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// No update endpoint: nothing here can change on the server, so the plan
	// stands. But EVERY Computed attribute is unknown in a plan, and a provider
	// must answer known values after an apply -- persisting the plan as it
	// stands earns "Provider returned invalid result object after apply". The
	// known values come from a read.
	var plan ApplicationsMetaInboundProtocolsOidcModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", "/applications/meta/inbound-protocols/oidc", nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading applications_meta_inbound_protocols_oidc", err.Error())
		return
	}

	var result client.OidcMetaData
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	plan.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ApplicationsMetaInboundProtocolsOidcResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *ApplicationsMetaInboundProtocolsOidcResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
