// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &ApplicationShareWithAllDataSource{}

func NewApplicationShareWithAllDataSource() datasource.DataSource {
	return &ApplicationShareWithAllDataSource{}
}

type ApplicationShareWithAllDataSource struct {
	client *client.Client
}

func (d *ApplicationShareWithAllDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application_share_with_all"
}

func (d *ApplicationShareWithAllDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a application_share_with_all data source.",
		Attributes: map[string]schema.Attribute{
			"status": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"details": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"application_id": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"policy": schema.StringAttribute{
				Required:    true,
				Description: "- ALL_EXISTING_ORGS_ONLY: Share with all organizations currently present. - ALL_EXISTING_AND_FUTURE_ORGS: Share with all current and any newly created organizations in future. ",
			},
			"role_sharing": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Required:    true,
				Description: "",
			},
		},
	}
}

func (d *ApplicationShareWithAllDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *ApplicationShareWithAllDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	resp.Diagnostics.AddError("Not Supported", "Read is not supported for application_share_with_all")
}
