// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationsMetaInboundProtocolsSamlModel is the Terraform model for applications_meta_inbound_protocols_saml.
type ApplicationsMetaInboundProtocolsSamlModel struct {
	DefaultNameIdFormat types.String `tfsdk:"default_name_id_format"`
	CertificateAlias jsontypes.Normalized `tfsdk:"certificate_alias"`
	ResponseSigningAlgorithm jsontypes.Normalized `tfsdk:"response_signing_algorithm"`
	ResponseDigestAlgorithm jsontypes.Normalized `tfsdk:"response_digest_algorithm"`
	AssertionEncryptionAlgorithm jsontypes.Normalized `tfsdk:"assertion_encryption_algorithm"`
	KeyEncryptionAlgorithm jsontypes.Normalized `tfsdk:"key_encryption_algorithm"`
}



// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationsMetaInboundProtocolsSamlModel) FromClientModel(c *client.SamlMetaData) {
	m.DefaultNameIdFormat = types.StringValue(c.DefaultNameIdFormat)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.CertificateAlias); err == nil {
		if m.CertificateAlias.IsNull() || m.CertificateAlias.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.CertificateAlias.ValueString()) {
			m.CertificateAlias = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.ResponseSigningAlgorithm); err == nil {
		if m.ResponseSigningAlgorithm.IsNull() || m.ResponseSigningAlgorithm.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.ResponseSigningAlgorithm.ValueString()) {
			m.ResponseSigningAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.ResponseDigestAlgorithm); err == nil {
		if m.ResponseDigestAlgorithm.IsNull() || m.ResponseDigestAlgorithm.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.ResponseDigestAlgorithm.ValueString()) {
			m.ResponseDigestAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.AssertionEncryptionAlgorithm); err == nil {
		if m.AssertionEncryptionAlgorithm.IsNull() || m.AssertionEncryptionAlgorithm.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.AssertionEncryptionAlgorithm.ValueString()) {
			m.AssertionEncryptionAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.KeyEncryptionAlgorithm); err == nil {
		if m.KeyEncryptionAlgorithm.IsNull() || m.KeyEncryptionAlgorithm.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.KeyEncryptionAlgorithm.ValueString()) {
			m.KeyEncryptionAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
