// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationAuthenticationSequenceScriptModel is the Terraform model for application_authentication_sequence_script.
type ApplicationAuthenticationSequenceScriptModel struct {
	Script types.String `tfsdk:"script"`
	ApplicationId types.String `tfsdk:"application_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *ApplicationAuthenticationSequenceScriptModel) ToClientModel() (*client.ScriptUpdateModel, error) {
	out := &client.ScriptUpdateModel{}
	if !m.Script.IsNull() && !m.Script.IsUnknown() {
		out.Script = m.Script.ValueString()
	}
	return out, nil
}


