// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationModel is the Terraform model for application.
type ApplicationModel struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	ApplicationVersion types.String `tfsdk:"application_version"`
	ImageUrl types.String `tfsdk:"image_url"`
	AccessUrl types.String `tfsdk:"access_url"`
	LogoutReturnUrl types.String `tfsdk:"logout_return_url"`
	ClientId types.String `tfsdk:"client_id"`
	Issuer types.String `tfsdk:"issuer"`
	Realm types.String `tfsdk:"realm"`
	TemplateId types.String `tfsdk:"template_id"`
	TemplateVersion types.String `tfsdk:"template_version"`
	IsManagementApp types.Bool `tfsdk:"is_management_app"`
	IsB2BSelfServiceApp types.Bool `tfsdk:"is_b2_b_self_service_app"`
	EnhancedOrgAuthenticationEnabled types.Bool `tfsdk:"enhanced_org_authentication_enabled"`
	ApplicationEnabled types.Bool `tfsdk:"application_enabled"`
	AssociatedRoles jsontypes.Normalized `tfsdk:"associated_roles"`
	ClaimConfiguration jsontypes.Normalized `tfsdk:"claim_configuration"`
	InboundProtocols jsontypes.Normalized `tfsdk:"inbound_protocols"`
	AuthenticationSequence jsontypes.Normalized `tfsdk:"authentication_sequence"`
	AdvancedConfigurations jsontypes.Normalized `tfsdk:"advanced_configurations"`
	ProvisioningConfigurations jsontypes.Normalized `tfsdk:"provisioning_configurations"`
	Access types.String `tfsdk:"access"`
	InboundProtocolConfiguration jsontypes.Normalized `tfsdk:"inbound_protocol_configuration"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *ApplicationModel) ToClientModel() (*client.ApplicationModel, error) {
	out := &client.ApplicationModel{}
	if !m.Id.IsNull() && !m.Id.IsUnknown() {
		out.Id = m.Id.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.ImageUrl.IsNull() && !m.ImageUrl.IsUnknown() {
		out.ImageUrl = m.ImageUrl.ValueString()
	}
	if !m.AccessUrl.IsNull() && !m.AccessUrl.IsUnknown() {
		out.AccessUrl = m.AccessUrl.ValueString()
	}
	if !m.LogoutReturnUrl.IsNull() && !m.LogoutReturnUrl.IsUnknown() {
		out.LogoutReturnUrl = m.LogoutReturnUrl.ValueString()
	}
	if !m.TemplateId.IsNull() && !m.TemplateId.IsUnknown() {
		out.TemplateId = m.TemplateId.ValueString()
	}
	if !m.TemplateVersion.IsNull() && !m.TemplateVersion.IsUnknown() {
		out.TemplateVersion = m.TemplateVersion.ValueString()
	}
	if !m.IsManagementApp.IsNull() && !m.IsManagementApp.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		IsManagementApp := m.IsManagementApp.ValueBool()
		out.IsManagementApp = &IsManagementApp
	}
	if !m.IsB2BSelfServiceApp.IsNull() && !m.IsB2BSelfServiceApp.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		IsB2BSelfServiceApp := m.IsB2BSelfServiceApp.ValueBool()
		out.IsB2BSelfServiceApp = &IsB2BSelfServiceApp
	}
	if !m.EnhancedOrgAuthenticationEnabled.IsNull() && !m.EnhancedOrgAuthenticationEnabled.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		EnhancedOrgAuthenticationEnabled := m.EnhancedOrgAuthenticationEnabled.ValueBool()
		out.EnhancedOrgAuthenticationEnabled = &EnhancedOrgAuthenticationEnabled
	}
	if !m.ApplicationEnabled.IsNull() && !m.ApplicationEnabled.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		ApplicationEnabled := m.ApplicationEnabled.ValueBool()
		out.ApplicationEnabled = &ApplicationEnabled
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.AssociatedRoles.IsNull() && !m.AssociatedRoles.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AssociatedRoles.ValueString()), &out.AssociatedRoles); err != nil {
			return out, fmt.Errorf("associated_roles: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.ClaimConfiguration.IsNull() && !m.ClaimConfiguration.IsUnknown() {
		if err := json.Unmarshal([]byte(m.ClaimConfiguration.ValueString()), &out.ClaimConfiguration); err != nil {
			return out, fmt.Errorf("claim_configuration: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.AuthenticationSequence.IsNull() && !m.AuthenticationSequence.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AuthenticationSequence.ValueString()), &out.AuthenticationSequence); err != nil {
			return out, fmt.Errorf("authentication_sequence: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.AdvancedConfigurations.IsNull() && !m.AdvancedConfigurations.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AdvancedConfigurations.ValueString()), &out.AdvancedConfigurations); err != nil {
			return out, fmt.Errorf("advanced_configurations: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.ProvisioningConfigurations.IsNull() && !m.ProvisioningConfigurations.IsUnknown() {
		if err := json.Unmarshal([]byte(m.ProvisioningConfigurations.ValueString()), &out.ProvisioningConfigurations); err != nil {
			return out, fmt.Errorf("provisioning_configurations: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.InboundProtocolConfiguration.IsNull() && !m.InboundProtocolConfiguration.IsUnknown() {
		if err := json.Unmarshal([]byte(m.InboundProtocolConfiguration.ValueString()), &out.InboundProtocolConfiguration); err != nil {
			return out, fmt.Errorf("inbound_protocol_configuration: %w", err)
		}
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: WSO2's ApplicationPatchModel has no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *ApplicationModel) ToUpdateModel() (*client.ApplicationPatchModel, error) {
	out := &client.ApplicationPatchModel{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.ApplicationVersion.IsNull() && !m.ApplicationVersion.IsUnknown() {
		out.ApplicationVersion = m.ApplicationVersion.ValueString()
	}
	if !m.ImageUrl.IsNull() && !m.ImageUrl.IsUnknown() {
		out.ImageUrl = m.ImageUrl.ValueString()
	}
	if !m.AccessUrl.IsNull() && !m.AccessUrl.IsUnknown() {
		out.AccessUrl = m.AccessUrl.ValueString()
	}
	if !m.LogoutReturnUrl.IsNull() && !m.LogoutReturnUrl.IsUnknown() {
		out.LogoutReturnUrl = m.LogoutReturnUrl.ValueString()
	}
	if !m.TemplateId.IsNull() && !m.TemplateId.IsUnknown() {
		out.TemplateId = m.TemplateId.ValueString()
	}
	if !m.TemplateVersion.IsNull() && !m.TemplateVersion.IsUnknown() {
		out.TemplateVersion = m.TemplateVersion.ValueString()
	}
	if !m.EnhancedOrgAuthenticationEnabled.IsNull() && !m.EnhancedOrgAuthenticationEnabled.IsUnknown() {
		EnhancedOrgAuthenticationEnabled := m.EnhancedOrgAuthenticationEnabled.ValueBool()
		out.EnhancedOrgAuthenticationEnabled = &EnhancedOrgAuthenticationEnabled
	}
	if !m.ApplicationEnabled.IsNull() && !m.ApplicationEnabled.IsUnknown() {
		ApplicationEnabled := m.ApplicationEnabled.ValueBool()
		out.ApplicationEnabled = &ApplicationEnabled
	}
	if !m.AssociatedRoles.IsNull() && !m.AssociatedRoles.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AssociatedRoles.ValueString()), &out.AssociatedRoles); err != nil {
			return out, fmt.Errorf("associated_roles: %w", err)
		}
	}
	if !m.ClaimConfiguration.IsNull() && !m.ClaimConfiguration.IsUnknown() {
		if err := json.Unmarshal([]byte(m.ClaimConfiguration.ValueString()), &out.ClaimConfiguration); err != nil {
			return out, fmt.Errorf("claim_configuration: %w", err)
		}
	}
	if !m.AuthenticationSequence.IsNull() && !m.AuthenticationSequence.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AuthenticationSequence.ValueString()), &out.AuthenticationSequence); err != nil {
			return out, fmt.Errorf("authentication_sequence: %w", err)
		}
	}
	if !m.AdvancedConfigurations.IsNull() && !m.AdvancedConfigurations.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AdvancedConfigurations.ValueString()), &out.AdvancedConfigurations); err != nil {
			return out, fmt.Errorf("advanced_configurations: %w", err)
		}
	}
	if !m.ProvisioningConfigurations.IsNull() && !m.ProvisioningConfigurations.IsUnknown() {
		if err := json.Unmarshal([]byte(m.ProvisioningConfigurations.ValueString()), &out.ProvisioningConfigurations); err != nil {
			return out, fmt.Errorf("provisioning_configurations: %w", err)
		}
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationModel) FromClientModel(c *client.ApplicationResponseModel) {
	m.Id = types.StringValue(c.Id)
	m.Name = types.StringValue(c.Name)
	m.Description = types.StringValue(c.Description)
	m.ApplicationVersion = types.StringValue(c.ApplicationVersion)
	m.ImageUrl = types.StringValue(c.ImageUrl)
	m.AccessUrl = types.StringValue(c.AccessUrl)
	m.LogoutReturnUrl = types.StringValue(c.LogoutReturnUrl)
	m.ClientId = types.StringValue(c.ClientId)
	m.Issuer = types.StringValue(c.Issuer)
	m.Realm = types.StringValue(c.Realm)
	m.TemplateId = types.StringValue(c.TemplateId)
	m.TemplateVersion = types.StringValue(c.TemplateVersion)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsManagementApp != nil {
		m.IsManagementApp = types.BoolValue(*c.IsManagementApp)
	} else if m.IsManagementApp.IsUnknown() {
		m.IsManagementApp = types.BoolNull()
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsB2BSelfServiceApp != nil {
		m.IsB2BSelfServiceApp = types.BoolValue(*c.IsB2BSelfServiceApp)
	} else if m.IsB2BSelfServiceApp.IsUnknown() {
		m.IsB2BSelfServiceApp = types.BoolNull()
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.EnhancedOrgAuthenticationEnabled != nil {
		m.EnhancedOrgAuthenticationEnabled = types.BoolValue(*c.EnhancedOrgAuthenticationEnabled)
	} else if m.EnhancedOrgAuthenticationEnabled.IsUnknown() {
		m.EnhancedOrgAuthenticationEnabled = types.BoolNull()
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.ApplicationEnabled != nil {
		m.ApplicationEnabled = types.BoolValue(*c.ApplicationEnabled)
	} else if m.ApplicationEnabled.IsUnknown() {
		m.ApplicationEnabled = types.BoolNull()
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.AssociatedRoles); err == nil {
		if m.AssociatedRoles.IsNull() || m.AssociatedRoles.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.AssociatedRoles.ValueString()) {
			m.AssociatedRoles = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.ClaimConfiguration); err == nil {
		if m.ClaimConfiguration.IsNull() || m.ClaimConfiguration.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.ClaimConfiguration.ValueString()) {
			m.ClaimConfiguration = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.InboundProtocols); err == nil {
		if m.InboundProtocols.IsNull() || m.InboundProtocols.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.InboundProtocols.ValueString()) {
			m.InboundProtocols = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.AuthenticationSequence); err == nil {
		if m.AuthenticationSequence.IsNull() || m.AuthenticationSequence.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.AuthenticationSequence.ValueString()) {
			m.AuthenticationSequence = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.AdvancedConfigurations); err == nil {
		if m.AdvancedConfigurations.IsNull() || m.AdvancedConfigurations.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.AdvancedConfigurations.ValueString()) {
			m.AdvancedConfigurations = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.ProvisioningConfigurations); err == nil {
		if m.ProvisioningConfigurations.IsNull() || m.ProvisioningConfigurations.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.ProvisioningConfigurations.ValueString()) {
			m.ProvisioningConfigurations = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.Access = types.StringValue(c.Access)
}
