// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &ApplicationInboundProtocolsSamlResource{}
var _ resource.ResourceWithImportState = &ApplicationInboundProtocolsSamlResource{}

func NewApplicationInboundProtocolsSamlResource() resource.Resource {
	return &ApplicationInboundProtocolsSamlResource{}
}

type ApplicationInboundProtocolsSamlResource struct {
	client *client.Client
}

func (r *ApplicationInboundProtocolsSamlResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application_inbound_protocols_saml"
}

func (r *ApplicationInboundProtocolsSamlResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a application_inbound_protocols_saml resource.",
		Attributes: map[string]schema.Attribute{
			"issuer": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"service_provider_qualifier": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"assertion_consumer_urls": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"default_assertion_consumer_url": schema.StringAttribute{
				Computed:    true,
				Description: "If not provided, the first assertion consumer URL on the assertionConsumerUrls will be picked as the default assertion consumer URL.",
			},
			"idp_entity_id_alias": schema.StringAttribute{
				Computed:    true,
				Description: "Default value is the IdP Entity ID value specified in Resident IdP.",
			},
			"single_sign_on_profile": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"attribute_profile": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"single_logout_profile": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"request_validation": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"response_signing": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"enable_assertion_query_profile": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"metadata_file": schema.StringAttribute{
				Optional:    true,
				Description: "",
			},
			"metadata_url": schema.StringAttribute{
				Optional:    true,
				Description: "",
			},
			"manual_configuration": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"application_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the applicationId.",
			},
		},
	}
}

func (r *ApplicationInboundProtocolsSamlResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *ApplicationInboundProtocolsSamlResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for application_inbound_protocols_saml")
}

func (r *ApplicationInboundProtocolsSamlResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ApplicationInboundProtocolsSamlModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.ApplicationId.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/applications/%v/inbound-protocols/saml", state.ApplicationId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading application_inbound_protocols_saml", err.Error())
		return
	}

	var result client.Saml2ServiceProvider
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ApplicationInboundProtocolsSamlResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ApplicationInboundProtocolsSamlModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state ApplicationInboundProtocolsSamlModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid application_inbound_protocols_saml configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PUT", fmt.Sprintf("/applications/%v/inbound-protocols/saml", state.ApplicationId.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating application_inbound_protocols_saml", err.Error())
		return
	}

	var result client.Saml2ServiceProvider
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	plan.FromClientModel(&result)

	tflog.Trace(ctx, "updated application_inbound_protocols_saml resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ApplicationInboundProtocolsSamlResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ApplicationInboundProtocolsSamlModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/applications/%v/inbound-protocols/saml", state.ApplicationId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting application_inbound_protocols_saml", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted application_inbound_protocols_saml resource")
}

func (r *ApplicationInboundProtocolsSamlResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("application_id"), req, resp)
}
