// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
)

// ApplicationsImportModel is the Terraform model for applications_import.
type ApplicationsImportModel struct {
}



