// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"


	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &ApplicationAuthenticationSequenceScriptResource{}
var _ resource.ResourceWithImportState = &ApplicationAuthenticationSequenceScriptResource{}

func NewApplicationAuthenticationSequenceScriptResource() resource.Resource {
	return &ApplicationAuthenticationSequenceScriptResource{}
}

type ApplicationAuthenticationSequenceScriptResource struct {
	client *client.Client
}

func (r *ApplicationAuthenticationSequenceScriptResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application_authentication_sequence_script"
}

func (r *ApplicationAuthenticationSequenceScriptResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a application_authentication_sequence_script resource.",
		Attributes: map[string]schema.Attribute{
			"script": schema.StringAttribute{
				Required:    true,
				Description: "Authentication Script to be updated.",
			},
			"application_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the applicationId.",
			},
		},
	}
}

func (r *ApplicationAuthenticationSequenceScriptResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *ApplicationAuthenticationSequenceScriptResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for application_authentication_sequence_script")
}

func (r *ApplicationAuthenticationSequenceScriptResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// No read endpoint available; keep existing state as-is.
}

func (r *ApplicationAuthenticationSequenceScriptResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ApplicationAuthenticationSequenceScriptModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid application_authentication_sequence_script configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PUT", fmt.Sprintf("/applications/%v/authenticationSequence/script", plan.ApplicationId.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating application_authentication_sequence_script", err.Error())
		return
	}

	_ = respBody

	tflog.Trace(ctx, "updated application_authentication_sequence_script resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ApplicationAuthenticationSequenceScriptResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *ApplicationAuthenticationSequenceScriptResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("application_id"), req, resp)
}
