// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &ApplicationsMetaInboundProtocolsSamlResource{}
var _ resource.ResourceWithImportState = &ApplicationsMetaInboundProtocolsSamlResource{}

func NewApplicationsMetaInboundProtocolsSamlResource() resource.Resource {
	return &ApplicationsMetaInboundProtocolsSamlResource{}
}

type ApplicationsMetaInboundProtocolsSamlResource struct {
	client *client.Client
}

func (r *ApplicationsMetaInboundProtocolsSamlResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_applications_meta_inbound_protocols_saml"
}

func (r *ApplicationsMetaInboundProtocolsSamlResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a applications_meta_inbound_protocols_saml resource.",
		Attributes: map[string]schema.Attribute{
			"default_name_id_format": schema.StringAttribute{
				Optional:    true,
				Description: "",
			},
			"certificate_alias": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"response_signing_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"response_digest_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"assertion_encryption_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"key_encryption_algorithm": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
		},
	}
}

func (r *ApplicationsMetaInboundProtocolsSamlResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *ApplicationsMetaInboundProtocolsSamlResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for applications_meta_inbound_protocols_saml")
}

func (r *ApplicationsMetaInboundProtocolsSamlResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ApplicationsMetaInboundProtocolsSamlModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", "/applications/meta/inbound-protocols/saml", nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading applications_meta_inbound_protocols_saml", err.Error())
		return
	}

	var result client.SamlMetaData
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ApplicationsMetaInboundProtocolsSamlResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// No update endpoint: nothing here can change on the server, so the plan
	// stands. But EVERY Computed attribute is unknown in a plan, and a provider
	// must answer known values after an apply -- persisting the plan as it
	// stands earns "Provider returned invalid result object after apply". The
	// known values come from a read.
	var plan ApplicationsMetaInboundProtocolsSamlModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", "/applications/meta/inbound-protocols/saml", nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading applications_meta_inbound_protocols_saml", err.Error())
		return
	}

	var result client.SamlMetaData
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	plan.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ApplicationsMetaInboundProtocolsSamlResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *ApplicationsMetaInboundProtocolsSamlResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
