// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
)

// ApplicationsMetaGroupModel is the Terraform model for applications_meta_group.
type ApplicationsMetaGroupModel struct {
}



