// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationsMetaInboundProtocolsOidcModel is the Terraform model for applications_meta_inbound_protocols_oidc.
type ApplicationsMetaInboundProtocolsOidcModel struct {
	AllowedGrantTypes jsontypes.Normalized `tfsdk:"allowed_grant_types"`
	DefaultUserAccessTokenExpiryTime types.String `tfsdk:"default_user_access_token_expiry_time"`
	DefaultApplicationAccessTokenExpiryTime types.String `tfsdk:"default_application_access_token_expiry_time"`
	DefaultRefreshTokenExpiryTime types.String `tfsdk:"default_refresh_token_expiry_time"`
	DefaultIdTokenExpiryTime types.String `tfsdk:"default_id_token_expiry_time"`
	IdTokenEncryptionAlgorithm jsontypes.Normalized `tfsdk:"id_token_encryption_algorithm"`
	IdTokenEncryptionMethod jsontypes.Normalized `tfsdk:"id_token_encryption_method"`
	ScopeValidators jsontypes.Normalized `tfsdk:"scope_validators"`
	AccessTokenType jsontypes.Normalized `tfsdk:"access_token_type"`
	AccessTokenBindingType jsontypes.Normalized `tfsdk:"access_token_binding_type"`
	TokenEndpointAuthMethod jsontypes.Normalized `tfsdk:"token_endpoint_auth_method"`
	TokenEndpointAllowReusePvtKeyJwt types.Bool `tfsdk:"token_endpoint_allow_reuse_pvt_key_jwt"`
	TokenEndpointSignatureAlgorithm jsontypes.Normalized `tfsdk:"token_endpoint_signature_algorithm"`
	IdTokenSignatureAlgorithm jsontypes.Normalized `tfsdk:"id_token_signature_algorithm"`
	RequestObjectSignatureAlgorithm jsontypes.Normalized `tfsdk:"request_object_signature_algorithm"`
	RequestObjectEncryptionAlgorithm jsontypes.Normalized `tfsdk:"request_object_encryption_algorithm"`
	RequestObjectEncryptionMethod jsontypes.Normalized `tfsdk:"request_object_encryption_method"`
	SubjectType jsontypes.Normalized `tfsdk:"subject_type"`
	FapiMetadata jsontypes.Normalized `tfsdk:"fapi_metadata"`
	CibaMetadata jsontypes.Normalized `tfsdk:"ciba_metadata"`
	AllowedIssuers jsontypes.Normalized `tfsdk:"allowed_issuers"`
}



// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationsMetaInboundProtocolsOidcModel) FromClientModel(c *client.OidcMetaData) {
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.AllowedGrantTypes); err == nil {
		if m.AllowedGrantTypes.IsNull() || m.AllowedGrantTypes.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.AllowedGrantTypes.ValueString()) {
			m.AllowedGrantTypes = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.DefaultUserAccessTokenExpiryTime = types.StringValue(c.DefaultUserAccessTokenExpiryTime)
	m.DefaultApplicationAccessTokenExpiryTime = types.StringValue(c.DefaultApplicationAccessTokenExpiryTime)
	m.DefaultRefreshTokenExpiryTime = types.StringValue(c.DefaultRefreshTokenExpiryTime)
	m.DefaultIdTokenExpiryTime = types.StringValue(c.DefaultIdTokenExpiryTime)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.IdTokenEncryptionAlgorithm); err == nil {
		if m.IdTokenEncryptionAlgorithm.IsNull() || m.IdTokenEncryptionAlgorithm.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.IdTokenEncryptionAlgorithm.ValueString()) {
			m.IdTokenEncryptionAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.IdTokenEncryptionMethod); err == nil {
		if m.IdTokenEncryptionMethod.IsNull() || m.IdTokenEncryptionMethod.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.IdTokenEncryptionMethod.ValueString()) {
			m.IdTokenEncryptionMethod = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.ScopeValidators); err == nil {
		if m.ScopeValidators.IsNull() || m.ScopeValidators.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.ScopeValidators.ValueString()) {
			m.ScopeValidators = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.AccessTokenType); err == nil {
		if m.AccessTokenType.IsNull() || m.AccessTokenType.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.AccessTokenType.ValueString()) {
			m.AccessTokenType = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.AccessTokenBindingType); err == nil {
		if m.AccessTokenBindingType.IsNull() || m.AccessTokenBindingType.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.AccessTokenBindingType.ValueString()) {
			m.AccessTokenBindingType = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.TokenEndpointAuthMethod); err == nil {
		if m.TokenEndpointAuthMethod.IsNull() || m.TokenEndpointAuthMethod.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.TokenEndpointAuthMethod.ValueString()) {
			m.TokenEndpointAuthMethod = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.TokenEndpointAllowReusePvtKeyJwt != nil {
		m.TokenEndpointAllowReusePvtKeyJwt = types.BoolValue(*c.TokenEndpointAllowReusePvtKeyJwt)
	} else if m.TokenEndpointAllowReusePvtKeyJwt.IsUnknown() {
		m.TokenEndpointAllowReusePvtKeyJwt = types.BoolNull()
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.TokenEndpointSignatureAlgorithm); err == nil {
		if m.TokenEndpointSignatureAlgorithm.IsNull() || m.TokenEndpointSignatureAlgorithm.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.TokenEndpointSignatureAlgorithm.ValueString()) {
			m.TokenEndpointSignatureAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.IdTokenSignatureAlgorithm); err == nil {
		if m.IdTokenSignatureAlgorithm.IsNull() || m.IdTokenSignatureAlgorithm.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.IdTokenSignatureAlgorithm.ValueString()) {
			m.IdTokenSignatureAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.RequestObjectSignatureAlgorithm); err == nil {
		if m.RequestObjectSignatureAlgorithm.IsNull() || m.RequestObjectSignatureAlgorithm.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.RequestObjectSignatureAlgorithm.ValueString()) {
			m.RequestObjectSignatureAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.RequestObjectEncryptionAlgorithm); err == nil {
		if m.RequestObjectEncryptionAlgorithm.IsNull() || m.RequestObjectEncryptionAlgorithm.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.RequestObjectEncryptionAlgorithm.ValueString()) {
			m.RequestObjectEncryptionAlgorithm = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.RequestObjectEncryptionMethod); err == nil {
		if m.RequestObjectEncryptionMethod.IsNull() || m.RequestObjectEncryptionMethod.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.RequestObjectEncryptionMethod.ValueString()) {
			m.RequestObjectEncryptionMethod = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.SubjectType); err == nil {
		if m.SubjectType.IsNull() || m.SubjectType.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.SubjectType.ValueString()) {
			m.SubjectType = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.FapiMetadata); err == nil {
		if m.FapiMetadata.IsNull() || m.FapiMetadata.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.FapiMetadata.ValueString()) {
			m.FapiMetadata = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.CibaMetadata); err == nil {
		if m.CibaMetadata.IsNull() || m.CibaMetadata.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.CibaMetadata.ValueString()) {
			m.CibaMetadata = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.AllowedIssuers); err == nil {
		if m.AllowedIssuers.IsNull() || m.AllowedIssuers.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.AllowedIssuers.ValueString()) {
			m.AllowedIssuers = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
