// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationLoginflowStatusModel is the Terraform model for application_loginflow_status.
type ApplicationLoginflowStatusModel struct {
	OperationId types.String `tfsdk:"operation_id"`
	Status types.String `tfsdk:"status"`
}


// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationLoginflowStatusModel) FromClientModel(c *client.LoginFlowStatusResponse) {
	m.OperationId = types.StringValue(c.OperationId)
}
