// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationsResidentModel is the Terraform model for applications_resident.
type ApplicationsResidentModel struct {
	ProvisioningConfigurations jsontypes.Normalized `tfsdk:"provisioning_configurations"`
	InboundProvisioning jsontypes.Normalized `tfsdk:"inbound_provisioning"`
	OutboundProvisioningIdps jsontypes.Normalized `tfsdk:"outbound_provisioning_idps"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *ApplicationsResidentModel) ToClientModel() (*client.ProvisioningConfiguration, error) {
	out := &client.ProvisioningConfiguration{}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.InboundProvisioning.IsNull() && !m.InboundProvisioning.IsUnknown() {
		if err := json.Unmarshal([]byte(m.InboundProvisioning.ValueString()), &out.InboundProvisioning); err != nil {
			return out, fmt.Errorf("inbound_provisioning: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.OutboundProvisioningIdps.IsNull() && !m.OutboundProvisioningIdps.IsUnknown() {
		if err := json.Unmarshal([]byte(m.OutboundProvisioningIdps.ValueString()), &out.OutboundProvisioningIdps); err != nil {
			return out, fmt.Errorf("outbound_provisioning_idps: %w", err)
		}
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationsResidentModel) FromClientModel(c *client.ResidentApplication) {
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.ProvisioningConfigurations); err == nil {
		m.ProvisioningConfigurations = jsontypes.NewNormalizedValue(string(encoded))
	}
}
