// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &ApplicationInboundProtocolOidcRevokeDataSource{}

func NewApplicationInboundProtocolOidcRevokeDataSource() datasource.DataSource {
	return &ApplicationInboundProtocolOidcRevokeDataSource{}
}

type ApplicationInboundProtocolOidcRevokeDataSource struct {
	client *client.Client
}

func (d *ApplicationInboundProtocolOidcRevokeDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application_inbound_protocol_oidc_revoke"
}

func (d *ApplicationInboundProtocolOidcRevokeDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a application_inbound_protocol_oidc_revoke data source.",
		Attributes: map[string]schema.Attribute{
			"application_id": schema.StringAttribute{
				Computed:    true,
				Description: "Identifier of the applicationId.",
			},
		},
	}
}

func (d *ApplicationInboundProtocolOidcRevokeDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *ApplicationInboundProtocolOidcRevokeDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	resp.Diagnostics.AddError("Not Supported", "Read is not supported for application_inbound_protocol_oidc_revoke")
}
