// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
)

// ApplicationMetaGroupModel is the Terraform model for application_meta_group.
type ApplicationMetaGroupModel struct {
}


