// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"


	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &ApplicationInboundProtocolPassiveStsResource{}
var _ resource.ResourceWithImportState = &ApplicationInboundProtocolPassiveStsResource{}

func NewApplicationInboundProtocolPassiveStsResource() resource.Resource {
	return &ApplicationInboundProtocolPassiveStsResource{}
}

type ApplicationInboundProtocolPassiveStsResource struct {
	client *client.Client
}

func (r *ApplicationInboundProtocolPassiveStsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application_inbound_protocol_passive_sts"
}

func (r *ApplicationInboundProtocolPassiveStsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a application_inbound_protocol_passive_sts resource.",
		Attributes: map[string]schema.Attribute{
			"realm": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"reply_to": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"reply_to_logout": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"application_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the applicationId.",
			},
		},
	}
}

func (r *ApplicationInboundProtocolPassiveStsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *ApplicationInboundProtocolPassiveStsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for application_inbound_protocol_passive_sts")
}

func (r *ApplicationInboundProtocolPassiveStsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ApplicationInboundProtocolPassiveStsModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.ApplicationId.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/applications/%v/inbound-protocols/passive-sts", state.ApplicationId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading application_inbound_protocol_passive_sts", err.Error())
		return
	}

	var result client.PassiveStsConfiguration
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ApplicationInboundProtocolPassiveStsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ApplicationInboundProtocolPassiveStsModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid application_inbound_protocol_passive_sts configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PUT", fmt.Sprintf("/applications/%v/inbound-protocols/passive-sts", plan.ApplicationId.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating application_inbound_protocol_passive_sts", err.Error())
		return
	}

	var result client.PassiveStsConfiguration
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	plan.FromClientModel(&result)

	tflog.Trace(ctx, "updated application_inbound_protocol_passive_sts resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ApplicationInboundProtocolPassiveStsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ApplicationInboundProtocolPassiveStsModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/applications/%v/inbound-protocols/passive-sts", state.ApplicationId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting application_inbound_protocol_passive_sts", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted application_inbound_protocol_passive_sts resource")
}

func (r *ApplicationInboundProtocolPassiveStsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("application_id"), req, resp)
}
