// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &ApplicationsMetaInboundProtocolResource{}
var _ resource.ResourceWithImportState = &ApplicationsMetaInboundProtocolResource{}

func NewApplicationsMetaInboundProtocolResource() resource.Resource {
	return &ApplicationsMetaInboundProtocolResource{}
}

type ApplicationsMetaInboundProtocolResource struct {
	client *client.Client
}

func (r *ApplicationsMetaInboundProtocolResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_applications_meta_inbound_protocol"
}

func (r *ApplicationsMetaInboundProtocolResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a applications_meta_inbound_protocol resource.",
		Attributes: map[string]schema.Attribute{
			"display_name": schema.StringAttribute{
				Optional:    true,
				Description: "",
			},
			"config_name": schema.StringAttribute{
				Optional:    true,
				Description: "",
			},
			"properties": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"inbound_protocol_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the inboundProtocolId.",
			},
		},
	}
}

func (r *ApplicationsMetaInboundProtocolResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *ApplicationsMetaInboundProtocolResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for applications_meta_inbound_protocol")
}

func (r *ApplicationsMetaInboundProtocolResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ApplicationsMetaInboundProtocolModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.InboundProtocolId.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/applications/meta/inbound-protocols/%v", state.InboundProtocolId.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading applications_meta_inbound_protocol", err.Error())
		return
	}

	var result client.CustomInboundProtocolMetaData
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ApplicationsMetaInboundProtocolResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// No update endpoint: nothing here can change on the server, so the plan
	// stands. But EVERY Computed attribute is unknown in a plan, and a provider
	// must answer known values after an apply -- persisting the plan as it
	// stands earns "Provider returned invalid result object after apply". The
	// known values come from a read.
	var plan ApplicationsMetaInboundProtocolModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifier off STATE, not the plan: it is Computed, so the plan has
	// it as unknown, and it cannot change on an update anyway.
	var state ApplicationsMetaInboundProtocolModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/applications/meta/inbound-protocols/%v", state.InboundProtocolId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading applications_meta_inbound_protocol", err.Error())
		return
	}

	var result client.CustomInboundProtocolMetaData
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	plan.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ApplicationsMetaInboundProtocolResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *ApplicationsMetaInboundProtocolResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("inbound_protocol_id"), req, resp)
}
