// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ApplicationInboundProtocolsOidcRevokeModel is the Terraform model for application_inbound_protocols_oidc_revoke.
type ApplicationInboundProtocolsOidcRevokeModel struct {
	ApplicationId types.String `tfsdk:"application_id"`
}



