// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// ApplicationLoginflowGenerateModel is the Terraform model for application_loginflow_generate.
type ApplicationLoginflowGenerateModel struct {
	OperationId types.String `tfsdk:"operation_id"`
	AvailableAuthenticators types.String `tfsdk:"available_authenticators"`
	UserClaims jsontypes.Normalized `tfsdk:"user_claims"`
	UserQuery types.String `tfsdk:"user_query"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *ApplicationLoginflowGenerateModel) ToClientModel() (*client.LoginFlowGenerateRequest, error) {
	out := &client.LoginFlowGenerateRequest{}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.UserClaims.IsNull() && !m.UserClaims.IsUnknown() {
		if err := json.Unmarshal([]byte(m.UserClaims.ValueString()), &out.UserClaims); err != nil {
			return out, fmt.Errorf("user_claims: %w", err)
		}
	}
	if !m.UserQuery.IsNull() && !m.UserQuery.IsUnknown() {
		out.UserQuery = m.UserQuery.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *ApplicationLoginflowGenerateModel) FromClientModel(c *client.LoginFlowGenerateResponse) {
	m.OperationId = types.StringValue(c.OperationId)
}
