// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// IdentityProviderFederatedAuthenticatorModel is the Terraform model for identity_provider_federated_authenticator.
type IdentityProviderFederatedAuthenticatorModel struct {
	AuthenticatorId types.String `tfsdk:"authenticator_id"`
	Name types.String `tfsdk:"name"`
	IsEnabled types.Bool `tfsdk:"is_enabled"`
	DefinedBy types.String `tfsdk:"defined_by"`
	IsDefault types.Bool `tfsdk:"is_default"`
	Tags jsontypes.Normalized `tfsdk:"tags"`
	Properties jsontypes.Normalized `tfsdk:"properties"`
	Endpoint jsontypes.Normalized `tfsdk:"endpoint"`
	IdentityProviderId types.String `tfsdk:"identity_provider_id"`
	FederatedAuthenticatorId types.String `tfsdk:"federated_authenticator_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *IdentityProviderFederatedAuthenticatorModel) ToClientModel() (*client.FederatedAuthenticatorPutRequest, error) {
	out := &client.FederatedAuthenticatorPutRequest{}
	if !m.AuthenticatorId.IsNull() && !m.AuthenticatorId.IsUnknown() {
		out.AuthenticatorId = m.AuthenticatorId.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.IsEnabled.IsNull() && !m.IsEnabled.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		IsEnabled := m.IsEnabled.ValueBool()
		out.IsEnabled = &IsEnabled
	}
	if !m.DefinedBy.IsNull() && !m.DefinedBy.IsUnknown() {
		out.DefinedBy = m.DefinedBy.ValueString()
	}
	if !m.IsDefault.IsNull() && !m.IsDefault.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		IsDefault := m.IsDefault.ValueBool()
		out.IsDefault = &IsDefault
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Properties.IsNull() && !m.Properties.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Properties.ValueString()), &out.Properties); err != nil {
			return out, fmt.Errorf("properties: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Endpoint.IsNull() && !m.Endpoint.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Endpoint.ValueString()), &out.Endpoint); err != nil {
			return out, fmt.Errorf("endpoint: %w", err)
		}
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *IdentityProviderFederatedAuthenticatorModel) FromClientModel(c *client.FederatedAuthenticator) {
	m.AuthenticatorId = types.StringValue(c.AuthenticatorId)
	m.Name = types.StringValue(c.Name)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsEnabled != nil {
		m.IsEnabled = types.BoolValue(*c.IsEnabled)
	} else if m.IsEnabled.IsUnknown() {
		m.IsEnabled = types.BoolNull()
	}
	m.DefinedBy = types.StringValue(c.DefinedBy)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsDefault != nil {
		m.IsDefault = types.BoolValue(*c.IsDefault)
	} else if m.IsDefault.IsUnknown() {
		m.IsDefault = types.BoolNull()
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Tags); err == nil {
		if m.Tags.IsNull() || m.Tags.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Tags.ValueString()) {
			m.Tags = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Properties); err == nil {
		if m.Properties.IsNull() || m.Properties.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Properties.ValueString()) {
			m.Properties = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Endpoint); err == nil {
		if m.Endpoint.IsNull() || m.Endpoint.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Endpoint.ValueString()) {
			m.Endpoint = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
