// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// IdentityProviderExportModel is the Terraform model for identity_provider_export.
type IdentityProviderExportModel struct {
	IdentityProviderId types.String `tfsdk:"identity_provider_id"`
}



