// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
)

// IdentityProvidersImportModel is the Terraform model for identity_providers_import.
type IdentityProvidersImportModel struct {
}



