// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// IdentityProviderShareModel is the Terraform model for identity_provider_share.
type IdentityProviderShareModel struct {
	Links jsontypes.Normalized `tfsdk:"links"`
	SharingMode jsontypes.Normalized `tfsdk:"sharing_mode"`
	Organizations jsontypes.Normalized `tfsdk:"organizations"`
	IdentityProviderId types.String `tfsdk:"identity_provider_id"`
}



// FromClientModel updates the Terraform model from a client model.
func (m *IdentityProviderShareModel) FromClientModel(c *client.IdpSharedOrganizationsResponse) {
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Links); err == nil {
		if m.Links.IsNull() || m.Links.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Links.ValueString()) {
			m.Links = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.SharingMode); err == nil {
		if m.SharingMode.IsNull() || m.SharingMode.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.SharingMode.ValueString()) {
			m.SharingMode = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Organizations); err == nil {
		if m.Organizations.IsNull() || m.Organizations.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Organizations.ValueString()) {
			m.Organizations = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
