// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// IdentityProviderProvisioningJitModel is the Terraform model for identity_provider_provisioning_jit.
type IdentityProviderProvisioningJitModel struct {
	IsEnabled types.Bool `tfsdk:"is_enabled"`
	Scheme types.String `tfsdk:"scheme"`
	Userstore types.String `tfsdk:"userstore"`
	AssociateLocalUser types.Bool `tfsdk:"associate_local_user"`
	SkipJITForLookupFailure types.Bool `tfsdk:"skip_jit_for_lookup_failure"`
	AccountLookupAttributeMappings jsontypes.Normalized `tfsdk:"account_lookup_attribute_mappings"`
	AttributeSyncMethod types.String `tfsdk:"attribute_sync_method"`
	IdpGroupSyncMethod types.String `tfsdk:"idp_group_sync_method"`
	IdentityProviderId types.String `tfsdk:"identity_provider_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *IdentityProviderProvisioningJitModel) ToClientModel() (*client.JustInTimeProvisioning, error) {
	out := &client.JustInTimeProvisioning{}
	if !m.IsEnabled.IsNull() && !m.IsEnabled.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		IsEnabled := m.IsEnabled.ValueBool()
		out.IsEnabled = &IsEnabled
	}
	if !m.Scheme.IsNull() && !m.Scheme.IsUnknown() {
		out.Scheme = m.Scheme.ValueString()
	}
	if !m.Userstore.IsNull() && !m.Userstore.IsUnknown() {
		out.Userstore = m.Userstore.ValueString()
	}
	if !m.AssociateLocalUser.IsNull() && !m.AssociateLocalUser.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		AssociateLocalUser := m.AssociateLocalUser.ValueBool()
		out.AssociateLocalUser = &AssociateLocalUser
	}
	if !m.SkipJITForLookupFailure.IsNull() && !m.SkipJITForLookupFailure.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		SkipJITForLookupFailure := m.SkipJITForLookupFailure.ValueBool()
		out.SkipJITForLookupFailure = &SkipJITForLookupFailure
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.AccountLookupAttributeMappings.IsNull() && !m.AccountLookupAttributeMappings.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AccountLookupAttributeMappings.ValueString()), &out.AccountLookupAttributeMappings); err != nil {
			return out, fmt.Errorf("account_lookup_attribute_mappings: %w", err)
		}
	}
	if !m.AttributeSyncMethod.IsNull() && !m.AttributeSyncMethod.IsUnknown() {
		out.AttributeSyncMethod = m.AttributeSyncMethod.ValueString()
	}
	if !m.IdpGroupSyncMethod.IsNull() && !m.IdpGroupSyncMethod.IsUnknown() {
		out.IdpGroupSyncMethod = m.IdpGroupSyncMethod.ValueString()
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *IdentityProviderProvisioningJitModel) FromClientModel(c *client.JustInTimeProvisioning) {
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsEnabled != nil {
		m.IsEnabled = types.BoolValue(*c.IsEnabled)
	} else if m.IsEnabled.IsUnknown() {
		m.IsEnabled = types.BoolNull()
	}
	m.Scheme = types.StringValue(c.Scheme)
	m.Userstore = types.StringValue(c.Userstore)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.AssociateLocalUser != nil {
		m.AssociateLocalUser = types.BoolValue(*c.AssociateLocalUser)
	} else if m.AssociateLocalUser.IsUnknown() {
		m.AssociateLocalUser = types.BoolNull()
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.SkipJITForLookupFailure != nil {
		m.SkipJITForLookupFailure = types.BoolValue(*c.SkipJITForLookupFailure)
	} else if m.SkipJITForLookupFailure.IsUnknown() {
		m.SkipJITForLookupFailure = types.BoolNull()
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.AccountLookupAttributeMappings); err == nil {
		if m.AccountLookupAttributeMappings.IsNull() || m.AccountLookupAttributeMappings.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.AccountLookupAttributeMappings.ValueString()) {
			m.AccountLookupAttributeMappings = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.AttributeSyncMethod = types.StringValue(c.AttributeSyncMethod)
	m.IdpGroupSyncMethod = types.StringValue(c.IdpGroupSyncMethod)
}
