// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &IdentityProviderConnectedAppDataSource{}

func NewIdentityProviderConnectedAppDataSource() datasource.DataSource {
	return &IdentityProviderConnectedAppDataSource{}
}

type IdentityProviderConnectedAppDataSource struct {
	client *client.Client
}

func (d *IdentityProviderConnectedAppDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_identity_provider_connected_app"
}

func (d *IdentityProviderConnectedAppDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a identity_provider_connected_app data source.",
		Attributes: map[string]schema.Attribute{
			"total_results": schema.Int64Attribute{
				Computed:    true,
				Description: "",
			},
			"start_index": schema.Int64Attribute{
				Computed:    true,
				Description: "",
			},
			"api_count": schema.Int64Attribute{
				Computed:    true,
				Description: "",
			},
			"links": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"connected_apps": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"identity_provider_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the identity-provider.",
			},
		},
	}
}

func (d *IdentityProviderConnectedAppDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *IdentityProviderConnectedAppDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config IdentityProviderConnectedAppModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/identity-providers/%v/connected-apps", config.IdentityProviderId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading identity_provider_connected_app", err.Error())
		return
	}

	var result client.ConnectedApps
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read identity_provider_connected_app data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
