// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &IdentityProviderFederatedAuthenticatorDataSource{}

func NewIdentityProviderFederatedAuthenticatorDataSource() datasource.DataSource {
	return &IdentityProviderFederatedAuthenticatorDataSource{}
}

type IdentityProviderFederatedAuthenticatorDataSource struct {
	client *client.Client
}

func (d *IdentityProviderFederatedAuthenticatorDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_identity_provider_federated_authenticator"
}

func (d *IdentityProviderFederatedAuthenticatorDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a identity_provider_federated_authenticator data source.",
		Attributes: map[string]schema.Attribute{
			"authenticator_id": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"is_enabled": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"defined_by": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"is_default": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"tags": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"properties": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"endpoint": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"identity_provider_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the parent identity-provider.",
			},
			"federated_authenticator_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the federated-authenticator.",
			},
		},
	}
}

func (d *IdentityProviderFederatedAuthenticatorDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *IdentityProviderFederatedAuthenticatorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config IdentityProviderFederatedAuthenticatorModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/identity-providers/%v/federated-authenticators/%v", config.IdentityProviderId.ValueString(), config.FederatedAuthenticatorId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading identity_provider_federated_authenticator", err.Error())
		return
	}

	var result client.FederatedAuthenticator
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read identity_provider_federated_authenticator data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
