// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// IdentityProviderImplicitAssociationModel is the Terraform model for identity_provider_implicit_association.
type IdentityProviderImplicitAssociationModel struct {
	IsEnabled types.Bool `tfsdk:"is_enabled"`
	LookupAttribute jsontypes.Normalized `tfsdk:"lookup_attribute"`
	IdentityProviderId types.String `tfsdk:"identity_provider_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *IdentityProviderImplicitAssociationModel) ToClientModel() (*client.AssociationRequest, error) {
	out := &client.AssociationRequest{}
	if !m.IsEnabled.IsNull() && !m.IsEnabled.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		IsEnabled := m.IsEnabled.ValueBool()
		out.IsEnabled = &IsEnabled
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.LookupAttribute.IsNull() && !m.LookupAttribute.IsUnknown() {
		if err := json.Unmarshal([]byte(m.LookupAttribute.ValueString()), &out.LookupAttribute); err != nil {
			return out, fmt.Errorf("lookup_attribute: %w", err)
		}
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *IdentityProviderImplicitAssociationModel) FromClientModel(c *client.AssociationResponse) {
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsEnabled != nil {
		m.IsEnabled = types.BoolValue(*c.IsEnabled)
	} else if m.IsEnabled.IsUnknown() {
		m.IsEnabled = types.BoolNull()
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.LookupAttribute); err == nil {
		if m.LookupAttribute.IsNull() || m.LookupAttribute.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.LookupAttribute.ValueString()) {
			m.LookupAttribute = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
