// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// IdentityProvidersUnshareModel is the Terraform model for identity_providers_unshare.
type IdentityProvidersUnshareModel struct {
	Status types.String `tfsdk:"status"`
	Details types.String `tfsdk:"details"`
	IdentityProviderId types.String `tfsdk:"identity_provider_id"`
	OrgIds jsontypes.Normalized `tfsdk:"org_ids"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *IdentityProvidersUnshareModel) ToClientModel() (*client.IdentityProviderUnshareSelectedRequestBody, error) {
	out := &client.IdentityProviderUnshareSelectedRequestBody{}
	if !m.IdentityProviderId.IsNull() && !m.IdentityProviderId.IsUnknown() {
		out.IdentityProviderId = m.IdentityProviderId.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.OrgIds.IsNull() && !m.OrgIds.IsUnknown() {
		if err := json.Unmarshal([]byte(m.OrgIds.ValueString()), &out.OrgIds); err != nil {
			return out, fmt.Errorf("org_ids: %w", err)
		}
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *IdentityProvidersUnshareModel) FromClientModel(c *client.IdpProcessSuccessResponse) {
	m.Status = types.StringValue(c.Status)
	m.Details = types.StringValue(c.Details)
}
