// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// IdentityProviderClaimModel is the Terraform model for identity_provider_claim.
type IdentityProviderClaimModel struct {
	UserIdClaim jsontypes.Normalized `tfsdk:"user_id_claim"`
	RoleClaim jsontypes.Normalized `tfsdk:"role_claim"`
	Mappings jsontypes.Normalized `tfsdk:"mappings"`
	ProvisioningClaims jsontypes.Normalized `tfsdk:"provisioning_claims"`
	IdentityProviderId types.String `tfsdk:"identity_provider_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *IdentityProviderClaimModel) ToClientModel() (*client.Claims, error) {
	out := &client.Claims{}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.UserIdClaim.IsNull() && !m.UserIdClaim.IsUnknown() {
		if err := json.Unmarshal([]byte(m.UserIdClaim.ValueString()), &out.UserIdClaim); err != nil {
			return out, fmt.Errorf("user_id_claim: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.RoleClaim.IsNull() && !m.RoleClaim.IsUnknown() {
		if err := json.Unmarshal([]byte(m.RoleClaim.ValueString()), &out.RoleClaim); err != nil {
			return out, fmt.Errorf("role_claim: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Mappings.IsNull() && !m.Mappings.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Mappings.ValueString()), &out.Mappings); err != nil {
			return out, fmt.Errorf("mappings: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.ProvisioningClaims.IsNull() && !m.ProvisioningClaims.IsUnknown() {
		if err := json.Unmarshal([]byte(m.ProvisioningClaims.ValueString()), &out.ProvisioningClaims); err != nil {
			return out, fmt.Errorf("provisioning_claims: %w", err)
		}
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *IdentityProviderClaimModel) FromClientModel(c *client.Claims) {
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.UserIdClaim); err == nil {
		if m.UserIdClaim.IsNull() || m.UserIdClaim.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.UserIdClaim.ValueString()) {
			m.UserIdClaim = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.RoleClaim); err == nil {
		if m.RoleClaim.IsNull() || m.RoleClaim.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.RoleClaim.ValueString()) {
			m.RoleClaim = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Mappings); err == nil {
		if m.Mappings.IsNull() || m.Mappings.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Mappings.ValueString()) {
			m.Mappings = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.ProvisioningClaims); err == nil {
		if m.ProvisioningClaims.IsNull() || m.ProvisioningClaims.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.ProvisioningClaims.ValueString()) {
			m.ProvisioningClaims = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
