// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// IdentityProvidersTemplateModel is the Terraform model for identity_providers_template.
type IdentityProvidersTemplateModel struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	Image types.String `tfsdk:"image"`
	Category types.String `tfsdk:"category"`
	DisplayOrder types.Int64 `tfsdk:"display_order"`
	Idp jsontypes.Normalized `tfsdk:"idp"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *IdentityProvidersTemplateModel) ToClientModel() (*client.IdentityProviderTemplate, error) {
	out := &client.IdentityProviderTemplate{}
	if !m.Id.IsNull() && !m.Id.IsUnknown() {
		out.Id = m.Id.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.Image.IsNull() && !m.Image.IsUnknown() {
		out.Image = m.Image.ValueString()
	}
	if !m.Category.IsNull() && !m.Category.IsUnknown() {
		out.Category = m.Category.ValueString()
	}
	if !m.DisplayOrder.IsNull() && !m.DisplayOrder.IsUnknown() {
		out.DisplayOrder = int32(m.DisplayOrder.ValueInt64())
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Idp.IsNull() && !m.Idp.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Idp.ValueString()), &out.Idp); err != nil {
			return out, fmt.Errorf("idp: %w", err)
		}
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *IdentityProvidersTemplateModel) FromClientModel(c *client.IdentityProviderTemplate) {
	m.Id = types.StringValue(c.Id)
	m.Name = types.StringValue(c.Name)
	m.Description = types.StringValue(c.Description)
	m.Image = types.StringValue(c.Image)
	m.Category = types.StringValue(c.Category)
	m.DisplayOrder = types.Int64Value(int64(c.DisplayOrder))
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Idp); err == nil {
		if m.Idp.IsNull() || m.Idp.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Idp.ValueString()) {
			m.Idp = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
