// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"


	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &IdentityProviderGroupResource{}
var _ resource.ResourceWithImportState = &IdentityProviderGroupResource{}

func NewIdentityProviderGroupResource() resource.Resource {
	return &IdentityProviderGroupResource{}
}

type IdentityProviderGroupResource struct {
	client *client.Client
}

func (r *IdentityProviderGroupResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_identity_provider_group"
}

func (r *IdentityProviderGroupResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a identity_provider_group resource.",
		Attributes: map[string]schema.Attribute{
			"identity_provider_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the identity-provider.",
			},
		},
	}
}

func (r *IdentityProviderGroupResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *IdentityProviderGroupResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for identity_provider_group")
}

func (r *IdentityProviderGroupResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state IdentityProviderGroupModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.IdentityProviderId.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/identity-providers/%v/groups", state.IdentityProviderId.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading identity_provider_group", err.Error())
		return
	}

	_ = respBody

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *IdentityProviderGroupResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan IdentityProviderGroupModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state IdentityProviderGroupModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// This operation takes no request body.
	var reqBody interface{}

	respBody, err := r.client.DoRequest(ctx, "PUT", fmt.Sprintf("/identity-providers/%v/groups", state.IdentityProviderId.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating identity_provider_group", err.Error())
		return
	}

	_ = respBody

	tflog.Trace(ctx, "updated identity_provider_group resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *IdentityProviderGroupResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *IdentityProviderGroupResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("identity_provider_id"), req, resp)
}
