// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// IdentityProvidersUnshareWithAllModel is the Terraform model for identity_providers_unshare_with_all.
type IdentityProvidersUnshareWithAllModel struct {
	Status types.String `tfsdk:"status"`
	Details types.String `tfsdk:"details"`
	IdentityProviderId types.String `tfsdk:"identity_provider_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *IdentityProvidersUnshareWithAllModel) ToClientModel() (*client.IdentityProviderUnshareAllRequestBody, error) {
	out := &client.IdentityProviderUnshareAllRequestBody{}
	if !m.IdentityProviderId.IsNull() && !m.IdentityProviderId.IsUnknown() {
		out.IdentityProviderId = m.IdentityProviderId.ValueString()
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *IdentityProvidersUnshareWithAllModel) FromClientModel(c *client.IdpProcessSuccessResponse) {
	m.Status = types.StringValue(c.Status)
	m.Details = types.StringValue(c.Details)
}
