// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// IdentityProviderModel is the Terraform model for identity_provider.
type IdentityProviderModel struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	TemplateId types.String `tfsdk:"template_id"`
	IsEnabled types.Bool `tfsdk:"is_enabled"`
	IsPrimary types.Bool `tfsdk:"is_primary"`
	IsShared types.Bool `tfsdk:"is_shared"`
	Image types.String `tfsdk:"image"`
	IsFederationHub types.Bool `tfsdk:"is_federation_hub"`
	HomeRealmIdentifier types.String `tfsdk:"home_realm_identifier"`
	Certificate jsontypes.Normalized `tfsdk:"certificate"`
	Alias types.String `tfsdk:"alias"`
	IdpIssuerName types.String `tfsdk:"idp_issuer_name"`
	Claims jsontypes.Normalized `tfsdk:"claims"`
	Roles jsontypes.Normalized `tfsdk:"roles"`
	Groups jsontypes.Normalized `tfsdk:"groups"`
	FederatedAuthenticators jsontypes.Normalized `tfsdk:"federated_authenticators"`
	Provisioning jsontypes.Normalized `tfsdk:"provisioning"`
	ImplicitAssociation jsontypes.Normalized `tfsdk:"implicit_association"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *IdentityProviderModel) ToClientModel() (*client.IdentityProviderPostRequest, error) {
	out := &client.IdentityProviderPostRequest{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.TemplateId.IsNull() && !m.TemplateId.IsUnknown() {
		out.TemplateId = m.TemplateId.ValueString()
	}
	if !m.IsPrimary.IsNull() && !m.IsPrimary.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		IsPrimary := m.IsPrimary.ValueBool()
		out.IsPrimary = &IsPrimary
	}
	if !m.Image.IsNull() && !m.Image.IsUnknown() {
		out.Image = m.Image.ValueString()
	}
	if !m.IsFederationHub.IsNull() && !m.IsFederationHub.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		IsFederationHub := m.IsFederationHub.ValueBool()
		out.IsFederationHub = &IsFederationHub
	}
	if !m.HomeRealmIdentifier.IsNull() && !m.HomeRealmIdentifier.IsUnknown() {
		out.HomeRealmIdentifier = m.HomeRealmIdentifier.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Certificate.IsNull() && !m.Certificate.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Certificate.ValueString()), &out.Certificate); err != nil {
			return out, fmt.Errorf("certificate: %w", err)
		}
	}
	if !m.Alias.IsNull() && !m.Alias.IsUnknown() {
		out.Alias = m.Alias.ValueString()
	}
	if !m.IdpIssuerName.IsNull() && !m.IdpIssuerName.IsUnknown() {
		out.IdpIssuerName = m.IdpIssuerName.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Claims.IsNull() && !m.Claims.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Claims.ValueString()), &out.Claims); err != nil {
			return out, fmt.Errorf("claims: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Roles.IsNull() && !m.Roles.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Roles.ValueString()), &out.Roles); err != nil {
			return out, fmt.Errorf("roles: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Groups.IsNull() && !m.Groups.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Groups.ValueString()), &out.Groups); err != nil {
			return out, fmt.Errorf("groups: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.FederatedAuthenticators.IsNull() && !m.FederatedAuthenticators.IsUnknown() {
		if err := json.Unmarshal([]byte(m.FederatedAuthenticators.ValueString()), &out.FederatedAuthenticators); err != nil {
			return out, fmt.Errorf("federated_authenticators: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Provisioning.IsNull() && !m.Provisioning.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Provisioning.ValueString()), &out.Provisioning); err != nil {
			return out, fmt.Errorf("provisioning: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.ImplicitAssociation.IsNull() && !m.ImplicitAssociation.IsUnknown() {
		if err := json.Unmarshal([]byte(m.ImplicitAssociation.ValueString()), &out.ImplicitAssociation); err != nil {
			return out, fmt.Errorf("implicit_association: %w", err)
		}
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *IdentityProviderModel) FromClientModel(c *client.IdentityProviderResponse) {
	m.Id = types.StringValue(c.Id)
	m.Name = types.StringValue(c.Name)
	m.Description = types.StringValue(c.Description)
	m.TemplateId = types.StringValue(c.TemplateId)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsEnabled != nil {
		m.IsEnabled = types.BoolValue(*c.IsEnabled)
	} else if m.IsEnabled.IsUnknown() {
		m.IsEnabled = types.BoolNull()
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsPrimary != nil {
		m.IsPrimary = types.BoolValue(*c.IsPrimary)
	} else if m.IsPrimary.IsUnknown() {
		m.IsPrimary = types.BoolNull()
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsShared != nil {
		m.IsShared = types.BoolValue(*c.IsShared)
	} else if m.IsShared.IsUnknown() {
		m.IsShared = types.BoolNull()
	}
	m.Image = types.StringValue(c.Image)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsFederationHub != nil {
		m.IsFederationHub = types.BoolValue(*c.IsFederationHub)
	} else if m.IsFederationHub.IsUnknown() {
		m.IsFederationHub = types.BoolNull()
	}
	m.HomeRealmIdentifier = types.StringValue(c.HomeRealmIdentifier)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Certificate); err == nil {
		if m.Certificate.IsNull() || m.Certificate.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Certificate.ValueString()) {
			m.Certificate = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.Alias = types.StringValue(c.Alias)
	m.IdpIssuerName = types.StringValue(c.IdpIssuerName)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Claims); err == nil {
		if m.Claims.IsNull() || m.Claims.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Claims.ValueString()) {
			m.Claims = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Roles); err == nil {
		if m.Roles.IsNull() || m.Roles.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Roles.ValueString()) {
			m.Roles = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Groups); err == nil {
		if m.Groups.IsNull() || m.Groups.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Groups.ValueString()) {
			m.Groups = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.FederatedAuthenticators.IsUnknown() {
		m.FederatedAuthenticators = jsontypes.NewNormalizedNull()
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.Provisioning.IsUnknown() {
		m.Provisioning = jsontypes.NewNormalizedNull()
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.ImplicitAssociation.IsUnknown() {
		m.ImplicitAssociation = jsontypes.NewNormalizedNull()
	}
}
