// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"


	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &IdentityProviderImportResource{}
var _ resource.ResourceWithImportState = &IdentityProviderImportResource{}

func NewIdentityProviderImportResource() resource.Resource {
	return &IdentityProviderImportResource{}
}

type IdentityProviderImportResource struct {
	client *client.Client
}

func (r *IdentityProviderImportResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_identity_provider_import"
}

func (r *IdentityProviderImportResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a identity_provider_import resource.",
		Attributes: map[string]schema.Attribute{
			"identity_provider_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the identity-provider.",
			},
		},
	}
}

func (r *IdentityProviderImportResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *IdentityProviderImportResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for identity_provider_import")
}

func (r *IdentityProviderImportResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// No read endpoint available; keep existing state as-is.
}

func (r *IdentityProviderImportResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan IdentityProviderImportModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state IdentityProviderImportModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// This operation takes no request body.
	var reqBody interface{}

	respBody, err := r.client.DoRequest(ctx, "PUT", fmt.Sprintf("/identity-providers/%v/import", state.IdentityProviderId.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating identity_provider_import", err.Error())
		return
	}

	_ = respBody

	tflog.Trace(ctx, "updated identity_provider_import resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *IdentityProviderImportResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *IdentityProviderImportResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("identity_provider_id"), req, resp)
}
