// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &IdentityProviderProvisioningJitDataSource{}

func NewIdentityProviderProvisioningJitDataSource() datasource.DataSource {
	return &IdentityProviderProvisioningJitDataSource{}
}

type IdentityProviderProvisioningJitDataSource struct {
	client *client.Client
}

func (d *IdentityProviderProvisioningJitDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_identity_provider_provisioning_jit"
}

func (d *IdentityProviderProvisioningJitDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a identity_provider_provisioning_jit data source.",
		Attributes: map[string]schema.Attribute{
			"is_enabled": schema.BoolAttribute{
				Required:    true,
				Description: "",
			},
			"scheme": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"userstore": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"associate_local_user": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"skip_jit_for_lookup_failure": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"account_lookup_attribute_mappings": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "List of local and federated attributes to be used for account lookup. The maximum number of mappings is 2. ",
			},
			"attribute_sync_method": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"idp_group_sync_method": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"identity_provider_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the identity-provider.",
			},
		},
	}
}

func (d *IdentityProviderProvisioningJitDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *IdentityProviderProvisioningJitDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config IdentityProviderProvisioningJitModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/identity-providers/%v/provisioning/jit", config.IdentityProviderId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading identity_provider_provisioning_jit", err.Error())
		return
	}

	var result client.JustInTimeProvisioning
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read identity_provider_provisioning_jit data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
