// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &IdentityProviderResource{}
var _ resource.ResourceWithImportState = &IdentityProviderResource{}

func NewIdentityProviderResource() resource.Resource {
	return &IdentityProviderResource{}
}

type IdentityProviderResource struct {
	client *client.Client
}

func (r *IdentityProviderResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_identity_provider"
}

func (r *IdentityProviderResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a identity_provider resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"template_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"is_enabled": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"is_primary": schema.BoolAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"is_shared": schema.BoolAttribute{
				Computed:    true,
				Description: "Whether this connection is a shared connection resolved from a parent organization. Present (and true) only for shared connections; omitted otherwise.",
			},
			"image": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"is_federation_hub": schema.BoolAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"home_realm_identifier": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"certificate": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"alias": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"idp_issuer_name": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"claims": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"roles": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"groups": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "IdP groups supported by the IdP.",
			},
			"federated_authenticators": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"provisioning": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"implicit_association": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
		},
	}
}

func (r *IdentityProviderResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *IdentityProviderResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan IdentityProviderModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid identity_provider configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", "/identity-providers", reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating identity_provider", err.Error())
		return
	}

	// A create that answers 201 with nothing but a Location header -- WSO2 does
	// this for tenants and applications. The identifier is in that header, and
	// everything else the server assigned has to be fetched.
	if len(respBody) == 0 {
		plan.Id = types.StringValue(client.IDFromLocation(location))

		respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/identity-providers/%v", plan.Id.ValueString()), nil)
		if err != nil {
			resp.Diagnostics.AddError("Error reading back the created identity_provider", err.Error())
			return
		}
	}

	if len(respBody) > 0 {
		var result client.IdentityProviderResponse
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created identity_provider resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *IdentityProviderResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state IdentityProviderModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.Id.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/identity-providers/%v", state.Id.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading identity_provider", err.Error())
		return
	}

	var result client.IdentityProviderResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *IdentityProviderResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan IdentityProviderModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state IdentityProviderModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid identity_provider configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PATCH", fmt.Sprintf("/identity-providers/%v", state.Id.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating identity_provider", err.Error())
		return
	}

	// An update that answers no body: PUT /tenants/{id}/owners/{id} is a 200
	// and nothing, every time. Unmarshalling that is "Error parsing response"
	// AFTER the server has already accepted the change -- so the write looks
	// like a failure and the new value never reaches state.
	if len(respBody) == 0 {
		respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/identity-providers/%v", state.Id.ValueString()), nil)
		if err != nil {
			resp.Diagnostics.AddError("Error reading back the updated identity_provider", err.Error())
			return
		}
	}

	if len(respBody) > 0 {
		var result client.IdentityProviderResponse
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "updated identity_provider resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *IdentityProviderResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state IdentityProviderModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/identity-providers/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting identity_provider", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted identity_provider resource")
}

func (r *IdentityProviderResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
