// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// IdentityProviderProvisioningModel is the Terraform model for identity_provider_provisioning.
type IdentityProviderProvisioningModel struct {
	Jit jsontypes.Normalized `tfsdk:"jit"`
	OutboundConnectors jsontypes.Normalized `tfsdk:"outbound_connectors"`
	IdentityProviderId types.String `tfsdk:"identity_provider_id"`
}



// FromClientModel updates the Terraform model from a client model.
func (m *IdentityProviderProvisioningModel) FromClientModel(c *client.ProvisioningResponse) {
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Jit); err == nil {
		if m.Jit.IsNull() || m.Jit.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Jit.ValueString()) {
			m.Jit = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.OutboundConnectors); err == nil {
		if m.OutboundConnectors.IsNull() || m.OutboundConnectors.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.OutboundConnectors.ValueString()) {
			m.OutboundConnectors = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
