// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// IdentityProviderProvisioningOutboundConnectorModel is the Terraform model for identity_provider_provisioning_outbound_connector.
type IdentityProviderProvisioningOutboundConnectorModel struct {
	ConnectorId types.String `tfsdk:"connector_id"`
	Name types.String `tfsdk:"name"`
	IsEnabled types.Bool `tfsdk:"is_enabled"`
	IsDefault types.Bool `tfsdk:"is_default"`
	BlockingEnabled types.Bool `tfsdk:"blocking_enabled"`
	RulesEnabled types.Bool `tfsdk:"rules_enabled"`
	Properties jsontypes.Normalized `tfsdk:"properties"`
	IdentityProviderId types.String `tfsdk:"identity_provider_id"`
	OutboundProvisioningConnectorId types.String `tfsdk:"outbound_provisioning_connector_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *IdentityProviderProvisioningOutboundConnectorModel) ToClientModel() (*client.OutboundConnectorPutRequest, error) {
	out := &client.OutboundConnectorPutRequest{}
	if !m.ConnectorId.IsNull() && !m.ConnectorId.IsUnknown() {
		out.ConnectorId = m.ConnectorId.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.IsEnabled.IsNull() && !m.IsEnabled.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		IsEnabled := m.IsEnabled.ValueBool()
		out.IsEnabled = &IsEnabled
	}
	if !m.IsDefault.IsNull() && !m.IsDefault.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		IsDefault := m.IsDefault.ValueBool()
		out.IsDefault = &IsDefault
	}
	if !m.BlockingEnabled.IsNull() && !m.BlockingEnabled.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		BlockingEnabled := m.BlockingEnabled.ValueBool()
		out.BlockingEnabled = &BlockingEnabled
	}
	if !m.RulesEnabled.IsNull() && !m.RulesEnabled.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		RulesEnabled := m.RulesEnabled.ValueBool()
		out.RulesEnabled = &RulesEnabled
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Properties.IsNull() && !m.Properties.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Properties.ValueString()), &out.Properties); err != nil {
			return out, fmt.Errorf("properties: %w", err)
		}
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *IdentityProviderProvisioningOutboundConnectorModel) FromClientModel(c *client.OutboundConnector) {
	m.ConnectorId = types.StringValue(c.ConnectorId)
	m.Name = types.StringValue(c.Name)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsEnabled != nil {
		m.IsEnabled = types.BoolValue(*c.IsEnabled)
	} else if m.IsEnabled.IsUnknown() {
		m.IsEnabled = types.BoolNull()
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsDefault != nil {
		m.IsDefault = types.BoolValue(*c.IsDefault)
	} else if m.IsDefault.IsUnknown() {
		m.IsDefault = types.BoolNull()
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.BlockingEnabled != nil {
		m.BlockingEnabled = types.BoolValue(*c.BlockingEnabled)
	} else if m.BlockingEnabled.IsUnknown() {
		m.BlockingEnabled = types.BoolNull()
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.RulesEnabled != nil {
		m.RulesEnabled = types.BoolValue(*c.RulesEnabled)
	} else if m.RulesEnabled.IsUnknown() {
		m.RulesEnabled = types.BoolNull()
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Properties); err == nil {
		if m.Properties.IsNull() || m.Properties.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Properties.ValueString()) {
			m.Properties = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
