// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// OrganizationModel is the Terraform model for organization.
type OrganizationModel struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	OrgHandle types.String `tfsdk:"org_handle"`
	Description types.String `tfsdk:"description"`
	Status types.String `tfsdk:"status"`
	Version types.String `tfsdk:"version"`
	Created types.String `tfsdk:"created"`
	LastModified types.String `tfsdk:"last_modified"`
	Type types.String `tfsdk:"type"`
	HasChildren types.Bool `tfsdk:"has_children"`
	Parent jsontypes.Normalized `tfsdk:"parent"`
	Attributes jsontypes.Normalized `tfsdk:"attributes"`
	Permissions jsontypes.Normalized `tfsdk:"permissions"`
	AncestorPath jsontypes.Normalized `tfsdk:"ancestor_path"`
	ParentId types.String `tfsdk:"parent_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *OrganizationModel) ToClientModel() (*client.OrganizationPostRequest, error) {
	out := &client.OrganizationPostRequest{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.OrgHandle.IsNull() && !m.OrgHandle.IsUnknown() {
		out.OrgHandle = m.OrgHandle.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		out.Type = m.Type.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Attributes.IsNull() && !m.Attributes.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Attributes.ValueString()), &out.Attributes); err != nil {
			return out, fmt.Errorf("attributes: %w", err)
		}
	}
	if !m.ParentId.IsNull() && !m.ParentId.IsUnknown() {
		out.ParentId = m.ParentId.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: WSO2's ApplicationPatchModel has no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *OrganizationModel) ToUpdateModel() (*client.OrganizationPutRequest, error) {
	out := &client.OrganizationPutRequest{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.Status.IsNull() && !m.Status.IsUnknown() {
		out.Status = m.Status.ValueString()
	}
	if !m.Version.IsNull() && !m.Version.IsUnknown() {
		out.Version = m.Version.ValueString()
	}
	if !m.Attributes.IsNull() && !m.Attributes.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Attributes.ValueString()), &out.Attributes); err != nil {
			return out, fmt.Errorf("attributes: %w", err)
		}
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *OrganizationModel) FromClientModel(c *client.GetOrganizationResponse) {
	m.Id = types.StringValue(c.Id)
	m.Name = types.StringValue(c.Name)
	m.OrgHandle = types.StringValue(c.OrgHandle)
	m.Description = types.StringValue(c.Description)
	m.Status = types.StringValue(c.Status)
	m.Version = types.StringValue(c.Version)
	m.Created = types.StringValue(c.Created)
	m.LastModified = types.StringValue(c.LastModified)
	m.Type = types.StringValue(c.Type)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.HasChildren != nil {
		m.HasChildren = types.BoolValue(*c.HasChildren)
	} else if m.HasChildren.IsUnknown() {
		m.HasChildren = types.BoolNull()
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.Parent); err == nil {
		m.Parent = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.Attributes); err == nil {
		m.Attributes = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.Permissions); err == nil {
		m.Permissions = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.AncestorPath); err == nil {
		m.AncestorPath = jsontypes.NewNormalizedValue(string(encoded))
	}
}
