// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// OrganizationDiscoveryModel is the Terraform model for organization_discovery.
type OrganizationDiscoveryModel struct {
	Attributes jsontypes.Normalized `tfsdk:"attributes"`
	OrganizationId types.String `tfsdk:"organization_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *OrganizationDiscoveryModel) ToClientModel() (*client.OrganizationDiscoveryAttributes, error) {
	out := &client.OrganizationDiscoveryAttributes{}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Attributes.IsNull() && !m.Attributes.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Attributes.ValueString()), &out.Attributes); err != nil {
			return out, fmt.Errorf("attributes: %w", err)
		}
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *OrganizationDiscoveryModel) FromClientModel(c *client.OrganizationDiscoveryAttributes) {
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.Attributes); err == nil {
		m.Attributes = jsontypes.NewNormalizedValue(string(encoded))
	}
}
