// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &OrganizationResource{}
var _ resource.ResourceWithImportState = &OrganizationResource{}

func NewOrganizationResource() resource.Resource {
	return &OrganizationResource{}
}

type OrganizationResource struct {
	client *client.Client
}

func (r *OrganizationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organization"
}

func (r *OrganizationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a organization resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"org_handle": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"status": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"version": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"created": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"last_modified": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"type": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"has_children": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"parent": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"attributes": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"permissions": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"ancestor_path": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Ancestors up to the request initiated organization",
			},
			"parent_id": schema.StringAttribute{
				Optional:    true,
				Description: "If the parentId is not present, Super will be taken as the parent organization.",
			},
		},
	}
}

func (r *OrganizationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *OrganizationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan OrganizationModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid organization configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", "/organizations", reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating organization", err.Error())
		return
	}

	// A create that answers 201 with nothing but a Location header -- WSO2 does
	// this for tenants and applications. The identifier is in that header, and
	// everything else the server assigned has to be fetched.
	if len(respBody) == 0 {
		plan.Id = types.StringValue(client.IDFromLocation(location))

		respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/organizations/%v", plan.Id.ValueString()), nil)
		if err != nil {
			resp.Diagnostics.AddError("Error reading back the created organization", err.Error())
			return
		}
	}

	if len(respBody) > 0 {
		var result client.GetOrganizationResponse
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created organization resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *OrganizationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state OrganizationModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.Id.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/organizations/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading organization", err.Error())
		return
	}

	var result client.GetOrganizationResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *OrganizationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan OrganizationModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state OrganizationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The UPDATE model, not the create one -- see ToUpdateModel.
	reqBody, err := plan.ToUpdateModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid organization configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PUT", fmt.Sprintf("/organizations/%v", state.Id.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating organization", err.Error())
		return
	}

	// An update that answers no body: PUT /tenants/{id}/owners/{id} is a 200
	// and nothing, every time. Unmarshalling that is "Error parsing response"
	// AFTER the server has already accepted the change -- so the write looks
	// like a failure and the new value never reaches state.
	if len(respBody) == 0 {
		respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/organizations/%v", state.Id.ValueString()), nil)
		if err != nil {
			resp.Diagnostics.AddError("Error reading back the updated organization", err.Error())
			return
		}
	}

	if len(respBody) > 0 {
		var result client.GetOrganizationResponse
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "updated organization resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *OrganizationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state OrganizationModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/organizations/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting organization", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted organization resource")
}

func (r *OrganizationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
