// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &OrganizationsCheckDiscoveryDataSource{}

func NewOrganizationsCheckDiscoveryDataSource() datasource.DataSource {
	return &OrganizationsCheckDiscoveryDataSource{}
}

type OrganizationsCheckDiscoveryDataSource struct {
	client *client.Client
}

func (d *OrganizationsCheckDiscoveryDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organizations_check_discovery"
}

func (d *OrganizationsCheckDiscoveryDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a organizations_check_discovery data source.",
		Attributes: map[string]schema.Attribute{
			"available": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"type": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"value": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
		},
	}
}

func (d *OrganizationsCheckDiscoveryDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *OrganizationsCheckDiscoveryDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	resp.Diagnostics.AddError("Not Supported", "Read is not supported for organizations_check_discovery")
}
