// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// OrganizationsCheckNameModel is the Terraform model for organizations_check_name.
type OrganizationsCheckNameModel struct {
	Available types.Bool `tfsdk:"available"`
	Name types.String `tfsdk:"name"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *OrganizationsCheckNameModel) ToClientModel() (*client.OrganizationNameCheckPostRequest, error) {
	out := &client.OrganizationNameCheckPostRequest{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *OrganizationsCheckNameModel) FromClientModel(c *client.OrganizationNameCheckPostResponse) {
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.Available != nil {
		m.Available = types.BoolValue(*c.Available)
	} else if m.Available.IsUnknown() {
		m.Available = types.BoolNull()
	}
}
