// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// OrganizationModel is the Terraform model for organization.
type OrganizationModel struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	OrgHandle types.String `tfsdk:"org_handle"`
	Description types.String `tfsdk:"description"`
	Status types.String `tfsdk:"status"`
	Version types.String `tfsdk:"version"`
	Created types.String `tfsdk:"created"`
	LastModified types.String `tfsdk:"last_modified"`
	Type types.String `tfsdk:"type"`
	HasChildren types.Bool `tfsdk:"has_children"`
	Parent types.String `tfsdk:"parent"`
	Attributes types.List `tfsdk:"attributes"`
	Permissions types.List `tfsdk:"permissions"`
	AncestorPath types.List `tfsdk:"ancestor_path"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *OrganizationModel) ToClientModel() *client.GetOrganizationResponse {
	out := &client.GetOrganizationResponse{}
	if !m.Id.IsNull() && !m.Id.IsUnknown() {
		out.Id = m.Id.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.OrgHandle.IsNull() && !m.OrgHandle.IsUnknown() {
		out.OrgHandle = m.OrgHandle.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.Status.IsNull() && !m.Status.IsUnknown() {
		out.Status = m.Status.ValueString()
	}
	if !m.Version.IsNull() && !m.Version.IsUnknown() {
		out.Version = m.Version.ValueString()
	}
	if !m.Created.IsNull() && !m.Created.IsUnknown() {
		out.Created = m.Created.ValueString()
	}
	if !m.LastModified.IsNull() && !m.LastModified.IsUnknown() {
		out.LastModified = m.LastModified.ValueString()
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		out.Type = m.Type.ValueString()
	}
	if !m.HasChildren.IsNull() && !m.HasChildren.IsUnknown() {
		out.HasChildren = m.HasChildren.ValueBool()
	}
	return out
}

// FromClientModel updates the Terraform model from a client model.
func (m *OrganizationModel) FromClientModel(c *client.GetOrganizationResponse) {
	m.Id = types.StringValue(c.Id)
	m.Name = types.StringValue(c.Name)
	m.OrgHandle = types.StringValue(c.OrgHandle)
	m.Description = types.StringValue(c.Description)
	m.Status = types.StringValue(c.Status)
	m.Version = types.StringValue(c.Version)
	m.Created = types.StringValue(c.Created)
	m.LastModified = types.StringValue(c.LastModified)
	m.Type = types.StringValue(c.Type)
	m.HasChildren = types.BoolValue(c.HasChildren)
}
