// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// OrganizationApplicationSharedAppModel is the Terraform model for organization_application_shared_app.
type OrganizationApplicationSharedAppModel struct {
	SharedApplications jsontypes.Normalized `tfsdk:"shared_applications"`
	OrganizationId types.String `tfsdk:"organization_id"`
	ApplicationId types.String `tfsdk:"application_id"`
}



// FromClientModel updates the Terraform model from a client model.
func (m *OrganizationApplicationSharedAppModel) FromClientModel(c *client.SharedApplicationsResponse) {
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.SharedApplications); err == nil {
		m.SharedApplications = jsontypes.NewNormalizedValue(string(encoded))
	}
}
