// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// OrganizationsMetaAttributeModel is the Terraform model for organizations_meta_attribute.
type OrganizationsMetaAttributeModel struct {
	Links jsontypes.Normalized `tfsdk:"links"`
	Attributes jsontypes.Normalized `tfsdk:"attributes"`
}



// FromClientModel updates the Terraform model from a client model.
func (m *OrganizationsMetaAttributeModel) FromClientModel(c *client.MetaAttributesResponse) {
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Links); err == nil {
		if m.Links.IsNull() || m.Links.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Links.ValueString()) {
			m.Links = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Attributes); err == nil {
		if m.Attributes.IsNull() || m.Attributes.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Attributes.ValueString()) {
			m.Attributes = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
