// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// OrganizationsCheckHandleModel is the Terraform model for organizations_check_handle.
type OrganizationsCheckHandleModel struct {
	Available types.Bool `tfsdk:"available"`
	OrgHandle types.String `tfsdk:"org_handle"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *OrganizationsCheckHandleModel) ToClientModel() (*client.OrganizationHandleCheckPostRequest, error) {
	out := &client.OrganizationHandleCheckPostRequest{}
	if !m.OrgHandle.IsNull() && !m.OrgHandle.IsUnknown() {
		out.OrgHandle = m.OrgHandle.ValueString()
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *OrganizationsCheckHandleModel) FromClientModel(c *client.OrganizationCheckResponse) {
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.Available != nil {
		m.Available = types.BoolValue(*c.Available)
	} else if m.Available.IsUnknown() {
		m.Available = types.BoolNull()
	}
}
