// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// OrganizationCheckHandleModel is the Terraform model for organization_check_handle.
type OrganizationCheckHandleModel struct {
	Available types.Bool `tfsdk:"available"`
	OrgHandle types.String `tfsdk:"org_handle"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *OrganizationCheckHandleModel) ToClientModel() (*client.OrganizationHandleCheckPostRequest, error) {
	out := &client.OrganizationHandleCheckPostRequest{}
	if !m.OrgHandle.IsNull() && !m.OrgHandle.IsUnknown() {
		out.OrgHandle = m.OrgHandle.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *OrganizationCheckHandleModel) FromClientModel(c *client.OrganizationCheckResponse) {
	m.Available = types.BoolValue(c.Available)
}
