// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// OrganizationMetaAttributeModel is the Terraform model for organization_meta_attribute.
type OrganizationMetaAttributeModel struct {
	Links jsontypes.Normalized `tfsdk:"links"`
	Attributes jsontypes.Normalized `tfsdk:"attributes"`
}


// FromClientModel updates the Terraform model from a client model.
func (m *OrganizationMetaAttributeModel) FromClientModel(c *client.MetaAttributesResponse) {
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.Links); err == nil {
		m.Links = jsontypes.NewNormalizedValue(string(encoded))
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	if encoded, err := json.Marshal(c.Attributes); err == nil {
		m.Attributes = jsontypes.NewNormalizedValue(string(encoded))
	}
}
