// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &OrganizationApplicationSharedAppDataSource{}

func NewOrganizationApplicationSharedAppDataSource() datasource.DataSource {
	return &OrganizationApplicationSharedAppDataSource{}
}

type OrganizationApplicationSharedAppDataSource struct {
	client *client.Client
}

func (d *OrganizationApplicationSharedAppDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organization_application_shared_app"
}

func (d *OrganizationApplicationSharedAppDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a organization_application_shared_app data source.",
		Attributes: map[string]schema.Attribute{
			"shared_applications": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"organization_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the parent organization.",
			},
			"application_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the application.",
			},
		},
	}
}

func (d *OrganizationApplicationSharedAppDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *OrganizationApplicationSharedAppDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OrganizationApplicationSharedAppModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/organizations/%v/applications/%v/shared-apps", config.OrganizationId.ValueString(), config.ApplicationId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading organization_application_shared_app", err.Error())
		return
	}

	var result client.SharedApplicationsResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read organization_application_shared_app data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
