// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"



	"github.com/hashicorp/terraform-plugin-log/tflog"


	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &OrganizationApplicationFragmentAppResource{}
var _ resource.ResourceWithImportState = &OrganizationApplicationFragmentAppResource{}

func NewOrganizationApplicationFragmentAppResource() resource.Resource {
	return &OrganizationApplicationFragmentAppResource{}
}

type OrganizationApplicationFragmentAppResource struct {
	client *client.Client
}

func (r *OrganizationApplicationFragmentAppResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organization_application_fragment_app"
}

func (r *OrganizationApplicationFragmentAppResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a organization_application_fragment_app resource.",
		Attributes: map[string]schema.Attribute{
			"organization_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the parent organization.",
			},
			"application_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the application.",
			},
		},
	}
}

func (r *OrganizationApplicationFragmentAppResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *OrganizationApplicationFragmentAppResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for organization_application_fragment_app")
}

func (r *OrganizationApplicationFragmentAppResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// No read endpoint available; keep existing state as-is.
}

func (r *OrganizationApplicationFragmentAppResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// No update endpoint: nothing here can change on the server, so the plan
	// stands. But EVERY Computed attribute is unknown in a plan, and a provider
	// must answer known values after an apply -- persisting the plan as it
	// stands earns "Provider returned invalid result object after apply". The
	// known values come from a read.
	var plan OrganizationApplicationFragmentAppModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *OrganizationApplicationFragmentAppResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state OrganizationApplicationFragmentAppModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/organizations/%v/applications/%v/fragment-apps", state.OrganizationId.ValueString(), state.ApplicationId.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting organization_application_fragment_app", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted organization_application_fragment_app resource")
}

func (r *OrganizationApplicationFragmentAppResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("application_id"), req, resp)
}
