// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ resource.Resource = &OrganizationsCheckNameResource{}
var _ resource.ResourceWithImportState = &OrganizationsCheckNameResource{}

func NewOrganizationsCheckNameResource() resource.Resource {
	return &OrganizationsCheckNameResource{}
}

type OrganizationsCheckNameResource struct {
	client *client.Client
}

func (r *OrganizationsCheckNameResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organizations_check_name"
}

func (r *OrganizationsCheckNameResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a organizations_check_name resource.",
		Attributes: map[string]schema.Attribute{
			"available": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Optional:    true,
				Description: "",
			},
		},
	}
}

func (r *OrganizationsCheckNameResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *OrganizationsCheckNameResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan OrganizationsCheckNameModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid organizations_check_name configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", "/organizations/check-name", reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating organizations_check_name", err.Error())
		return
	}

	// A create that answers 201 with nothing but a Location header -- WSO2 does
	// this for tenants and applications. The identifier is in that header, and
	// everything else the server assigned has to be fetched.
	if len(respBody) == 0 {
		// Nothing in this resource's schema holds an identifier, so the
		// Location header has nowhere to go.
		_ = location
	}

	if len(respBody) > 0 {
		var result client.OrganizationNameCheckPostResponse
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created organizations_check_name resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *OrganizationsCheckNameResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// No read endpoint available; keep existing state as-is.
}

func (r *OrganizationsCheckNameResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// No update endpoint: nothing here can change on the server, so the plan
	// stands. But EVERY Computed attribute is unknown in a plan, and a provider
	// must answer known values after an apply -- persisting the plan as it
	// stands earns "Provider returned invalid result object after apply". The
	// known values come from a read.
	var plan OrganizationsCheckNameModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *OrganizationsCheckNameResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *OrganizationsCheckNameResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
