// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &OrganizationApplicationShareDataSource{}

func NewOrganizationApplicationShareDataSource() datasource.DataSource {
	return &OrganizationApplicationShareDataSource{}
}

type OrganizationApplicationShareDataSource struct {
	client *client.Client
}

func (d *OrganizationApplicationShareDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organization_application_share"
}

func (d *OrganizationApplicationShareDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a organization_application_share data source.",
		Attributes: map[string]schema.Attribute{
			"share_with_all_children": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"shared_organizations": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"organization_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the parent organization.",
			},
			"application_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the parent application.",
			},
			"shared_organization_id": schema.StringAttribute{
				Computed:    true,
				Description: "Identifier of the shared-organization.",
			},
		},
	}
}

func (d *OrganizationApplicationShareDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *OrganizationApplicationShareDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	resp.Diagnostics.AddError("Not Supported", "Read is not supported for organization_application_share")
}
