// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ provider.Provider = &wso2Provider{}

type wso2Provider struct {
	version string
}

type wso2ProviderModel struct {
	Endpoint types.String `tfsdk:"endpoint"`
	ApiKey   types.String `tfsdk:"api_key"`
	Token    types.String `tfsdk:"token"`
	Username types.String `tfsdk:"username"`
	Password types.String `tfsdk:"password"`
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &wso2Provider{
			version: version,
		}
	}
}

func (p *wso2Provider) Metadata(_ context.Context, _ provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "wso2"
	resp.Version = p.version
}

func (p *wso2Provider) Schema(_ context.Context, _ provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"endpoint": schema.StringAttribute{
				Optional:    true,
				Description: "The API endpoint URL.",
			},
			"api_key": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "The API key for authentication.",
			},
			"token": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "The bearer token for authentication.",
			},
			"username": schema.StringAttribute{
				Optional:    true,
				Description: "The username for basic authentication.",
			},
			"password": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "The password for basic authentication.",
			},
		},
	}
}

func (p *wso2Provider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var config wso2ProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if config.Endpoint.IsUnknown() {
		resp.Diagnostics.AddWarning(
			"Unknown Endpoint Value",
			"The provider endpoint value is not yet known. Defaulting to the spec-defined base path.",
		)
	}

	endpoint := "https://localhost:9443/api/server/v1"
	if !config.Endpoint.IsNull() && !config.Endpoint.IsUnknown() {
		endpoint = config.Endpoint.ValueString()
	}

	c := client.NewClient(endpoint)

	if !config.ApiKey.IsNull() {
		c.ApiKey = config.ApiKey.ValueString()
	}
	if !config.Token.IsNull() {
		c.Token = config.Token.ValueString()
	}
	if !config.Username.IsNull() {
		c.Username = config.Username.ValueString()
	}
	if !config.Password.IsNull() {
		c.Password = config.Password.ValueString()
	}

	resp.DataSourceData = c
	resp.ResourceData = c
}

func (p *wso2Provider) Resources(_ context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewApplicationResource,
		NewApplicationImportResource,
		NewApplicationLoginflowGenerateResource,
		NewApplicationLoginflowResultResource,
		NewApplicationLoginflowStatusResource,
		NewApplicationMetaAdaptiveAuthTemplateResource,
		NewApplicationMetaGroupResource,
		NewApplicationMetaInboundProtocolResource,
		NewApplicationMetaInboundProtocolOidcResource,
		NewApplicationMetaInboundProtocolSamlResource,
		NewApplicationMetaInboundProtocolWsTrustResource,
		NewApplicationResidentResource,
		NewApplicationShareResource,
		NewApplicationShareWithAllResource,
		NewApplicationTemplateResource,
		NewApplicationUnshareResource,
		NewApplicationUnshareWithAllResource,
		NewApplicationAuthenticationSequenceScriptResource,
		NewApplicationAuthenticatorResource,
		NewApplicationAuthorizedResource,
		NewApplicationExportResource,
		NewApplicationExportFileResource,
		NewApplicationInboundProtocolResource,
		NewApplicationInboundProtocolResource,
		NewApplicationInboundProtocolOidcResource,
		NewApplicationInboundProtocolOidcRegenerateSecretResource,
		NewApplicationInboundProtocolOidcRevokeResource,
		NewApplicationInboundProtocolOidcSecretResource,
		NewApplicationInboundProtocolPassiveStsResource,
		NewApplicationInboundProtocolSamlResource,
		NewApplicationInboundProtocolWsTrustResource,
		NewApplicationOwnerResource,
		NewApplicationShareResource,
		NewApplicationSharedAppResource,
		NewChannelVerifiedTenantResource,
		NewOrganizationResource,
		NewOrganizationCheckDiscoveryResource,
		NewOrganizationCheckHandleResource,
		NewOrganizationCheckNameResource,
		NewOrganizationDiscoveryResource,
		NewOrganizationMetaAttributeResource,
		NewOrganizationMetadataResource,
		NewOrganizationSelfResource,
		NewOrganizationApplicationFragmentAppResource,
		NewOrganizationApplicationShareResource,
		NewOrganizationApplicationSharedAppResource,
		NewOrganizationDiscoveryResource,
		NewTenantResource,
		NewTenantDomainResource,
		NewTenantLifecycleStatusResource,
		NewTenantMetadataResource,
		NewTenantOwnerResource,
	}
}

func (p *wso2Provider) DataSources(_ context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewApplicationDataSource,
		NewApplicationImportDataSource,
		NewApplicationLoginflowGenerateDataSource,
		NewApplicationLoginflowResultDataSource,
		NewApplicationLoginflowStatusDataSource,
		NewApplicationMetaAdaptiveAuthTemplateDataSource,
		NewApplicationMetaGroupDataSource,
		NewApplicationMetaInboundProtocolDataSource,
		NewApplicationMetaInboundProtocolOidcDataSource,
		NewApplicationMetaInboundProtocolSamlDataSource,
		NewApplicationMetaInboundProtocolWsTrustDataSource,
		NewApplicationResidentDataSource,
		NewApplicationShareDataSource,
		NewApplicationShareWithAllDataSource,
		NewApplicationTemplateDataSource,
		NewApplicationUnshareDataSource,
		NewApplicationUnshareWithAllDataSource,
		NewApplicationAuthenticationSequenceScriptDataSource,
		NewApplicationAuthenticatorDataSource,
		NewApplicationAuthorizedDataSource,
		NewApplicationExportDataSource,
		NewApplicationExportFileDataSource,
		NewApplicationInboundProtocolDataSource,
		NewApplicationInboundProtocolDataSource,
		NewApplicationInboundProtocolOidcDataSource,
		NewApplicationInboundProtocolOidcRegenerateSecretDataSource,
		NewApplicationInboundProtocolOidcRevokeDataSource,
		NewApplicationInboundProtocolOidcSecretDataSource,
		NewApplicationInboundProtocolPassiveStsDataSource,
		NewApplicationInboundProtocolSamlDataSource,
		NewApplicationInboundProtocolWsTrustDataSource,
		NewApplicationOwnerDataSource,
		NewApplicationShareDataSource,
		NewApplicationSharedAppDataSource,
		NewChannelVerifiedTenantDataSource,
		NewOrganizationDataSource,
		NewOrganizationCheckDiscoveryDataSource,
		NewOrganizationCheckHandleDataSource,
		NewOrganizationCheckNameDataSource,
		NewOrganizationDiscoveryDataSource,
		NewOrganizationMetaAttributeDataSource,
		NewOrganizationMetadataDataSource,
		NewOrganizationSelfDataSource,
		NewOrganizationApplicationFragmentAppDataSource,
		NewOrganizationApplicationShareDataSource,
		NewOrganizationApplicationSharedAppDataSource,
		NewOrganizationDiscoveryDataSource,
		NewTenantDataSource,
		NewTenantDomainDataSource,
		NewTenantLifecycleStatusDataSource,
		NewTenantMetadataDataSource,
		NewTenantOwnerDataSource,
	}
}
