// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// TenantModel is the Terraform model for tenant.
type TenantModel struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Domain types.String `tfsdk:"domain"`
	Owners types.List `tfsdk:"owners"`
	CreatedDate types.String `tfsdk:"created_date"`
	LifecycleStatus types.String `tfsdk:"lifecycle_status"`
	Region types.String `tfsdk:"region"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *TenantModel) ToClientModel() *client.TenantResponseModel {
	out := &client.TenantResponseModel{}
	if !m.Id.IsNull() && !m.Id.IsUnknown() {
		out.Id = m.Id.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Domain.IsNull() && !m.Domain.IsUnknown() {
		out.Domain = m.Domain.ValueString()
	}
	if !m.CreatedDate.IsNull() && !m.CreatedDate.IsUnknown() {
		out.CreatedDate = m.CreatedDate.ValueString()
	}
	if !m.Region.IsNull() && !m.Region.IsUnknown() {
		out.Region = m.Region.ValueString()
	}
	return out
}

// FromClientModel updates the Terraform model from a client model.
func (m *TenantModel) FromClientModel(c *client.TenantResponseModel) {
	m.Id = types.StringValue(c.Id)
	m.Name = types.StringValue(c.Name)
	m.Domain = types.StringValue(c.Domain)
	m.CreatedDate = types.StringValue(c.CreatedDate)
	m.Region = types.StringValue(c.Region)
}
