// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &TenantLifecycleStatusDataSource{}

func NewTenantLifecycleStatusDataSource() datasource.DataSource {
	return &TenantLifecycleStatusDataSource{}
}

type TenantLifecycleStatusDataSource struct {
	client *client.Client
}

func (d *TenantLifecycleStatusDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tenant_lifecycle_status"
}

func (d *TenantLifecycleStatusDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a tenant_lifecycle_status data source.",
		Attributes: map[string]schema.Attribute{
			"activated": schema.StringAttribute{
				Computed:    true,
				Description: "Active status of the tenant.",
			},
			"tenant_id": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the tenant.",
			},
		},
	}
}

func (d *TenantLifecycleStatusDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *TenantLifecycleStatusDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	resp.Diagnostics.AddError("Not Supported", "Read is not supported for tenant_lifecycle_status")
}
