// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// TenantLifecycleStatusModel is the Terraform model for tenant_lifecycle_status.
type TenantLifecycleStatusModel struct {
	Activated types.Bool `tfsdk:"activated"`
	TenantId types.String `tfsdk:"tenant_id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *TenantLifecycleStatusModel) ToClientModel() (*client.TenantPutModel, error) {
	out := &client.TenantPutModel{}
	if !m.Activated.IsNull() && !m.Activated.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		Activated := m.Activated.ValueBool()
		out.Activated = &Activated
	}
	return out, nil
}


