// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

// TrustedTokenIssuerModel is the Terraform model for trusted_token_issuer.
type TrustedTokenIssuerModel struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	TemplateId types.String `tfsdk:"template_id"`
	IsEnabled types.Bool `tfsdk:"is_enabled"`
	IsPrimary types.Bool `tfsdk:"is_primary"`
	Image types.String `tfsdk:"image"`
	IsFederationHub types.Bool `tfsdk:"is_federation_hub"`
	HomeRealmIdentifier types.String `tfsdk:"home_realm_identifier"`
	Certificate jsontypes.Normalized `tfsdk:"certificate"`
	Alias types.String `tfsdk:"alias"`
	Issuer types.String `tfsdk:"issuer"`
	Claims jsontypes.Normalized `tfsdk:"claims"`
	Roles jsontypes.Normalized `tfsdk:"roles"`
	Groups jsontypes.Normalized `tfsdk:"groups"`
	FederatedAuthenticators jsontypes.Normalized `tfsdk:"federated_authenticators"`
	Provisioning jsontypes.Normalized `tfsdk:"provisioning"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *TrustedTokenIssuerModel) ToClientModel() (*client.TrustedTokenIssuerPostRequest, error) {
	out := &client.TrustedTokenIssuerPostRequest{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.TemplateId.IsNull() && !m.TemplateId.IsUnknown() {
		out.TemplateId = m.TemplateId.ValueString()
	}
	if !m.Image.IsNull() && !m.Image.IsUnknown() {
		out.Image = m.Image.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Certificate.IsNull() && !m.Certificate.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Certificate.ValueString()), &out.Certificate); err != nil {
			return out, fmt.Errorf("certificate: %w", err)
		}
	}
	if !m.Alias.IsNull() && !m.Alias.IsUnknown() {
		out.Alias = m.Alias.ValueString()
	}
	if !m.Issuer.IsNull() && !m.Issuer.IsUnknown() {
		out.Issuer = m.Issuer.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Claims.IsNull() && !m.Claims.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Claims.ValueString()), &out.Claims); err != nil {
			return out, fmt.Errorf("claims: %w", err)
		}
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *TrustedTokenIssuerModel) FromClientModel(c *client.TrustedTokenIssuerResponse) {
	m.Id = types.StringValue(c.Id)
	m.Name = types.StringValue(c.Name)
	m.Description = types.StringValue(c.Description)
	m.TemplateId = types.StringValue(c.TemplateId)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsEnabled != nil {
		m.IsEnabled = types.BoolValue(*c.IsEnabled)
	} else if m.IsEnabled.IsUnknown() {
		m.IsEnabled = types.BoolNull()
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsPrimary != nil {
		m.IsPrimary = types.BoolValue(*c.IsPrimary)
	} else if m.IsPrimary.IsUnknown() {
		m.IsPrimary = types.BoolNull()
	}
	m.Image = types.StringValue(c.Image)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsFederationHub != nil {
		m.IsFederationHub = types.BoolValue(*c.IsFederationHub)
	} else if m.IsFederationHub.IsUnknown() {
		m.IsFederationHub = types.BoolNull()
	}
	m.HomeRealmIdentifier = types.StringValue(c.HomeRealmIdentifier)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Certificate); err == nil {
		if m.Certificate.IsNull() || m.Certificate.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Certificate.ValueString()) {
			m.Certificate = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.Alias = types.StringValue(c.Alias)
	m.Issuer = types.StringValue(c.Issuer)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Claims); err == nil {
		if m.Claims.IsNull() || m.Claims.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Claims.ValueString()) {
			m.Claims = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Roles); err == nil {
		if m.Roles.IsNull() || m.Roles.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Roles.ValueString()) {
			m.Roles = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Groups); err == nil {
		if m.Groups.IsNull() || m.Groups.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Groups.ValueString()) {
			m.Groups = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.FederatedAuthenticators); err == nil {
		if m.FederatedAuthenticators.IsNull() || m.FederatedAuthenticators.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.FederatedAuthenticators.ValueString()) {
			m.FederatedAuthenticators = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Provisioning); err == nil {
		if m.Provisioning.IsNull() || m.Provisioning.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Provisioning.ValueString()) {
			m.Provisioning = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
