// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-wso2/internal/client"
)

var _ datasource.DataSource = &TrustedTokenIssuerDataSource{}

func NewTrustedTokenIssuerDataSource() datasource.DataSource {
	return &TrustedTokenIssuerDataSource{}
}

type TrustedTokenIssuerDataSource struct {
	client *client.Client
}

func (d *TrustedTokenIssuerDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_trusted_token_issuer"
}

func (d *TrustedTokenIssuerDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a trusted_token_issuer data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"template_id": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"is_enabled": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"is_primary": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"image": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"is_federation_hub": schema.BoolAttribute{
				Computed:    true,
				Description: "",
			},
			"home_realm_identifier": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"certificate": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Required:    true,
				Description: "",
			},
			"alias": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"issuer": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"claims": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"roles": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"groups": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "IdP groups supported by the IdP.",
			},
			"federated_authenticators": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"provisioning": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
		},
	}
}

func (d *TrustedTokenIssuerDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *TrustedTokenIssuerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config TrustedTokenIssuerModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/trusted-token-issuers/%v", config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading trusted_token_issuer", err.Error())
		return
	}

	var result client.TrustedTokenIssuerResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read trusted_token_issuer data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
